// Generated by npm run map:tiles from the seeded terrain painter.
export const MAP_TILES = {
    version: "beb1d583e41cc80d",
    bounds: {
        x: -59200,
        y: -53000,
        w: 119700,
        h: 103400,
    },
    tileSize: 256,
    gutter: 2,
    levels: [
        {
            level: 0,
            span: 119700,
        },
        {
            level: 1,
            span: 59850,
        },
        {
            level: 2,
            span: 29925,
        },
        {
            level: 3,
            span: 14962.5,
        },
        {
            level: 4,
            span: 7481.25,
        },
        {
            level: 5,
            span: 3740.625,
        },
        {
            level: 6,
            span: 1870.3125,
        },
    ],
    index: "index.json",
} as const;
