import type { Drawing, Family } from "./drawing";

/**
 * The one list of drawings, in the order the shelf shows them: by family, in the order of `FAMILIES`,
 * and then by id. It names each drawing by a loader and imports none, so a page pays only for the
 * drawings it draws. __tests__/catalog.test.ts holds every file in a family's folder to one line here.
 */
export const CATALOG = {
    animals: {
        animals: () => import("./animals/animals").then((m) => m.animals),
        dog: () => import("./animals/dog").then((m) => m.dog),
        mice: () => import("./animals/mice").then((m) => m.mice),
        flamingos: () => import("./animals/flamingos").then((m) => m.flamingos),
        gannet: () => import("./animals/gannet").then((m) => m.gannet),
        parakeets: () => import("./animals/parakeets").then((m) => m.parakeets),
        puffins: () => import("./animals/puffins").then((m) => m.puffins),
        swallows: () => import("./animals/swallows").then((m) => m.swallows),
        albatross: () => import("./animals/albatross").then((m) => m.albatross),
        badger: () => import("./animals/badger").then((m) => m.badger),
        goat: () => import("./animals/goat").then((m) => m.goat),
        owlflying: () => import("./animals/owlflying").then((m) => m.owlFlying),
        robin: () => import("./animals/robin").then((m) => m.robin),
        starlings: () => import("./animals/starlings").then((m) => m.starlings),
        ants: () => import("./animals/ants").then((m) => m.ants),
        bats: () => import("./animals/bats").then((m) => m.bats),
        birdrow: () => import("./animals/birdrow").then((m) => m.birdRow),
        bumblebee: () => import("./animals/bumblebee").then((m) => m.bumblebee),
        camel: () => import("./animals/camel").then((m) => m.camel),
        crabs: () => import("./animals/crabs").then((m) => m.crabs),
        dolphins: () => import("./animals/dolphins").then((m) => m.dolphins),
        dragonfly: () => import("./animals/dragonfly").then((m) => m.dragonfly),
        eagle: () => import("./animals/eagle").then((m) => m.eagle),
        fennec: () => import("./animals/fennec").then((m) => m.fennec),
        fishshoal: () => import("./animals/fishshoal").then((m) => m.fishShoal),
        fox: () => import("./animals/fox").then((m) => m.fox),
        geese: () => import("./animals/geese").then((m) => m.geese),
        glowworms: () => import("./animals/glowworms").then((m) => m.glowworms),
        gull: () => import("./animals/gull").then((m) => m.gull),
        heron: () => import("./animals/heron").then((m) => m.heron),
        kingfisher: () => import("./animals/kingfisher").then((m) => m.kingfisher),
        manta: () => import("./animals/manta").then((m) => m.manta),
        minibeasts: () => import("./animals/minibeasts").then((m) => m.minibeasts),
        octopus: () => import("./animals/octopus").then((m) => m.octopus),
        parrot: () => import("./animals/parrot").then((m) => m.parrot),
        rabbits: () => import("./animals/rabbits").then((m) => m.rabbits),
        seal: () => import("./animals/seal").then((m) => m.seal),
        seaturtle: () => import("./animals/seaturtle").then((m) => m.seaTurtle),
        starfish: () => import("./animals/starfish").then((m) => m.starfish),
        whale: () => import("./animals/whale").then((m) => m.whale),
        "svg.cat": () => import("./imported/svg.cat").then((m) => m.cat),
        "svg.duck": () => import("./imported/svg.duck").then((m) => m.duck),
        "svg.hen": () => import("./imported/svg.hen").then((m) => m.hen),
        "excalidraw.owl": () => import("./imported/excalidraw.owl").then((m) => m.owl),
        "strokes.hedgehog": () => import("./imported/strokes.hedgehog").then((m) => m.hedgehog),
        "svg.fish-tank": () => import("./imported/svg.fish-tank").then((m) => m.fishTank),
        fish: () => import("./animals/fish").then((m) => m.fish),
        sheep: () => import("./animals/sheep").then((m) => m.sheep),
        swimmingrabbit: () => import("./animals/swimmingrabbit").then((m) => m.swimmingRabbit),
    },
    people: {
        children: () => import("./people/children").then((m) => m.children),
        skater: () => import("./people/skater").then((m) => m.skater),
        face: () => import("./people/face").then((m) => m.face),
        person: () => import("./people/person").then((m) => m.person),
        umbrellas: () => import("./people/umbrellas").then((m) => m.umbrellas),
        heads: () => import("./people/heads").then((m) => m.headRow),
    },
    food: {
        basket: () => import("./food/basket").then((m) => m.basket),
        cake: () => import("./food/cake").then((m) => m.cake),
        plate: () => import("./food/plate").then((m) => m.plateOf),
        sweetjar: () => import("./food/sweetjar").then((m) => m.sweetJar),
        pizza: () => import("./food/pizza").then((m) => m.pizza),
        chocolate: () => import("./food/chocolate").then((m) => m.chocolateBar),
        eggbox: () => import("./food/eggbox").then((m) => m.eggBox),
        bakingtray: () => import("./food/bakingtray").then((m) => m.bakingTray),
        spoons: () => import("./food/spoons").then((m) => m.measuringSpoons),
        recipe: () => import("./food/recipe").then((m) => m.recipeCard),
        mixingbowl: () => import("./food/mixingbowl").then((m) => m.mixingBowl),
        pile: () => import("./food/pile").then((m) => m.ingredientPile),
        worktop: () => import("./food/worktop").then((m) => m.worktop),
        oven: () => import("./food/oven").then((m) => m.oven),
        "prop.apple": () => import("./food/prop.apple").then((m) => m.appleV),
        "svg.cup": () => import("./imported/svg.cup").then((m) => m.cup),
        "svg.kitchen-counter": () =>
            import("./imported/svg.kitchen-counter").then((m) => m.kitchenCounter),
        "svg.birthday-table": () =>
            import("./imported/svg.birthday-table").then((m) => m.birthdayTable),
        cakeknife: () => import("./food/cakeknife").then((m) => m.cakeKnife),
        longcake: () => import("./food/longcake").then((m) => m.longCake),
        carrot: () => import("./food/carrot").then((m) => m.carrot),
    },
    home: {
        balloons: () => import("./home/balloons").then((m) => m.balloons),
        bottle: () => import("./home/bottle").then((m) => m.bottle),
        bubbles: () => import("./home/bubbles").then((m) => m.bubbles),
        chest: () => import("./home/chest").then((m) => m.chest),
        clothesline: () => import("./home/clothesline").then((m) => m.clothesLine),
        easel: () => import("./home/easel").then((m) => m.easel),
        envelope: () => import("./home/envelope").then((m) => m.envelope),
        exercisebook: () => import("./home/exercisebook").then((m) => m.exerciseBook),
        lantern: () => import("./home/lantern").then((m) => m.lantern),
        poststamp: () => import("./home/poststamp").then((m) => m.postStamp),
        swing: () => import("./home/swing").then((m) => m.swing),
        tablet: () => import("./home/tablet").then((m) => m.familyTablet),
        "svg.kite": () => import("./imported/svg.kite").then((m) => m.kite),
        "strokes.bunting": () => import("./imported/strokes.bunting").then((m) => m.bunting),
        "svg.pencil": () => import("./imported/svg.pencil").then((m) => m.pencil),
        "svg.bedroom-shelf": () =>
            import("./imported/svg.bedroom-shelf").then((m) => m.bedroomShelf),
    },
    outdoors: {
        flowers: () => import("./outdoors/flowers").then((m) => m.flowerRow),
        snowman: () => import("./outdoors/snowman").then((m) => m.snowman),
        tree: () => import("./outdoors/tree").then((m) => m.tree),
        geyser: () => import("./outdoors/geyser").then((m) => m.geyser),
        giantflower: () => import("./outdoors/giantflower").then((m) => m.giantFlower),
        saltlake: () => import("./outdoors/saltlake").then((m) => m.saltLake),
        saltpans: () => import("./outdoors/saltpans").then((m) => m.saltPans),
        treeplatform: () => import("./outdoors/treeplatform").then((m) => m.treePlatform),
        hedge: () => import("./outdoors/hedge").then((m) => m.hedge),
        log: () => import("./outdoors/log").then((m) => m.fallenLog),
        shootingstar: () => import("./outdoors/shootingstar").then((m) => m.shootingStar),
        stile: () => import("./outdoors/stile").then((m) => m.stile),
        ammonite: () => import("./outdoors/ammonite").then((m) => m.ammonite),
        cobweb: () => import("./outdoors/cobweb").then((m) => m.cobweb),
        comet: () => import("./outdoors/comet").then((m) => m.comet),
        coral: () => import("./outdoors/coral").then((m) => m.coral),
        crops: () => import("./outdoors/crops").then((m) => m.crops),
        crystals: () => import("./outdoors/crystals").then((m) => m.crystals),
        dandelion: () => import("./outdoors/dandelion").then((m) => m.dandelion),
        daysky: () => import("./outdoors/daysky").then((m) => m.daySky),
        firs: () => import("./outdoors/firs").then((m) => m.firs),
        fossil: () => import("./outdoors/fossil").then((m) => m.fossil),
        frogcycle: () => import("./outdoors/frogcycle").then((m) => m.frogCycle),
        growstages: () => import("./outdoors/growstages").then((m) => m.growStages),
        iceberg: () => import("./outdoors/iceberg").then((m) => m.iceberg),
        leafrow: () => import("./outdoors/leafrow").then((m) => m.leafRow),
        moon: () => import("./outdoors/moon").then((m) => m.moonV),
        oasis: () => import("./outdoors/oasis").then((m) => m.oasis),
        palms: () => import("./outdoors/palms").then((m) => m.palms),
        peaks: () => import("./outdoors/peaks").then((m) => m.peaks),
        pond: () => import("./outdoors/pond").then((m) => m.pond),
        rainbow: () => import("./outdoors/rainbow").then((m) => m.rainbow),
        seasontrees: () => import("./outdoors/seasontrees").then((m) => m.seasonTrees),
        skyisland: () => import("./outdoors/skyisland").then((m) => m.skyIsland),
        stalactites: () => import("./outdoors/stalactites").then((m) => m.stalactites),
        strata: () => import("./outdoors/strata").then((m) => m.strata),
        toadstools: () => import("./outdoors/toadstools").then((m) => m.toadstools),
        volcano: () => import("./outdoors/volcano").then((m) => m.volcano),
        cloud: () => import("./outdoors/cloud").then((m) => m.cloud),
        tent: () => import("./outdoors/tent").then((m) => m.tent),
        "svg.sandcastle": () => import("./imported/svg.sandcastle").then((m) => m.sandcastle),
        "excalidraw.wheelbarrow": () =>
            import("./imported/excalidraw.wheelbarrow").then((m) => m.wheelbarrow),
        "strokes.sun": () => import("./imported/strokes.sun").then((m) => m.sun),
        "svg.treehouse": () => import("./imported/svg.treehouse").then((m) => m.treehouse),
        "excalidraw.garden": () => import("./imported/excalidraw.garden").then((m) => m.garden),
        "strokes.hills": () => import("./imported/strokes.hills").then((m) => m.hills),
        "arcade.ground": () => import("./outdoors/arcade.ground").then((m) => m.ground),
        meadow: () => import("./outdoors/meadow").then((m) => m.meadow),
        sea: () => import("./outdoors/sea").then((m) => m.sea),
        dig: () => import("./outdoors/dig").then((m) => m.digSpot),
        current: () => import("./outdoors/current").then((m) => m.current),
        reeds: () => import("./outdoors/reeds").then((m) => m.reeds),
        steppingstone: () => import("./outdoors/steppingstone").then((m) => m.steppingStone),
    },
    places: {
        bandstand: () => import("./places/bandstand").then((m) => m.bandstand),
        barn: () => import("./places/barn").then((m) => m.barn),
        carousel: () => import("./places/carousel").then((m) => m.carousel),
        citywalls: () => import("./places/citywalls").then((m) => m.cityWalls),
        cottage: () => import("./places/cottage").then((m) => m.cottage),
        gardengate: () => import("./places/gardengate").then((m) => m.gardenGate),
        hall: () => import("./places/hall").then((m) => m.hall),
        houses: () => import("./places/houses").then((m) => m.houses),
        hut: () => import("./places/hut").then((m) => m.hut),
        library: () => import("./places/library").then((m) => m.library),
        moorings: () => import("./places/moorings").then((m) => m.moorings),
        observatory: () => import("./places/observatory").then((m) => m.observatory),
        street: () => import("./places/street").then((m) => m.street),
        temple: () => import("./places/temple").then((m) => m.temple),
        tower: () => import("./places/tower").then((m) => m.tower),
        well: () => import("./places/well").then((m) => m.well),
        windmill: () => import("./places/windmill").then((m) => m.windmill),
        "world.door": () => import("./places/world.door").then((m) => m.doorV),
        "world.window": () => import("./places/world.window").then((m) => m.windowV),
        bookhouse: () => import("./places/bookhouse").then((m) => m.bookHouse),
        greatclock: () => import("./places/greatclock").then((m) => m.greatClock),
        lampstation: () => import("./places/lampstation").then((m) => m.lampStation),
        printingpress: () => import("./places/printingpress").then((m) => m.printingPress),
        lamppost: () => import("./places/lamppost").then((m) => m.lampPost),
        birdhide: () => import("./places/birdhide").then((m) => m.birdHide),
        bridge: () => import("./places/bridge").then((m) => m.bridge),
        jetty: () => import("./places/jetty").then((m) => m.jetty),
        lighthouse: () => import("./places/lighthouse").then((m) => m.lighthouse),
        station: () => import("./places/station").then((m) => m.station),
        clocktower: () => import("./places/clocktower").then((m) => m.clockTower),
        "svg.shop-front": () => import("./imported/svg.shop-front").then((m) => m.shopFront),
        sheeppen: () => import("./places/sheeppen").then((m) => m.sheepPen),
    },
    travel: {
        bus: () => import("./travel/bus").then((m) => m.bus),
        airship: () => import("./travel/airship").then((m) => m.airship),
        buoy: () => import("./travel/buoy").then((m) => m.buoy),
        mailboat: () => import("./travel/mailboat").then((m) => m.mailBoat),
        seaplane: () => import("./travel/seaplane").then((m) => m.seaplane),
        yachts: () => import("./travel/yachts").then((m) => m.yachts),
        cablecar: () => import("./travel/cablecar").then((m) => m.cableCar),
        railsignal: () => import("./travel/railsignal").then((m) => m.railSignal),
        shipwheel: () => import("./travel/shipwheel").then((m) => m.shipWheel),
        balloon: () => import("./travel/balloon").then((m) => m.balloon),
        canallock: () => import("./travel/canallock").then((m) => m.canalLock),
        carriage: () => import("./travel/carriage").then((m) => m.carriage),
        compass: () => import("./travel/compass").then((m) => m.compassRose),
        departureboard: () => import("./travel/departureboard").then((m) => m.departureBoard),
        divingbell: () => import("./travel/divingbell").then((m) => m.divingBell),
        ferry: () => import("./travel/ferry").then((m) => m.ferry),
        fuelgauge: () => import("./travel/fuelgauge").then((m) => m.fuelGauge),
        loco: () => import("./travel/loco").then((m) => m.loco),
        mapkey: () => import("./travel/mapkey").then((m) => m.mapKey),
        mapscale: () => import("./travel/mapscale").then((m) => m.mapScale),
        maptitle: () => import("./travel/maptitle").then((m) => m.mapTitle),
        narrowboat: () => import("./travel/narrowboat").then((m) => m.narrowboat),
        paperplane: () => import("./travel/paperplane").then((m) => m.paperPlane),
        roaddistances: () => import("./travel/roaddistances").then((m) => m.roadDistances),
        ropebridge: () => import("./travel/ropebridge").then((m) => m.ropeBridge),
        ship: () => import("./travel/ship").then((m) => m.ship),
        sidings: () => import("./travel/sidings").then((m) => m.sidings),
        signpost: () => import("./travel/signpost").then((m) => m.signpost),
        sledge: () => import("./travel/sledge").then((m) => m.sledge),
        suitcases: () => import("./travel/suitcases").then((m) => m.suitcases),
        ticket: () => import("./travel/ticket").then((m) => m.ticket),
        tractor: () => import("./travel/tractor").then((m) => m.tractor),
        train: () => import("./travel/train").then((m) => m.train),
        windsock: () => import("./travel/windsock").then((m) => m.windsock),
        gridmap: () => import("./travel/gridmap").then((m) => m.mapGrid),
        "svg.bicycle": () => import("./imported/svg.bicycle").then((m) => m.bicycle),
        "svg.rocket": () => import("./imported/svg.rocket").then((m) => m.rocket),
        "svg.boat": () => import("./imported/svg.boat").then((m) => m.boat),
        rocket: () => import("./travel/rocket").then((m) => m.rocket),
        "arcade.road": () => import("./travel/arcade.road").then((m) => m.road),
        raft: () => import("./travel/raft").then((m) => m.raft),
        railway: () => import("./travel/railway").then((m) => m.railway),
        liftpit: () => import("./travel/liftpit").then((m) => m.liftpit),
        yardlever: () => import("./travel/yardlever").then((m) => m.yardLever),
        coupling: () => import("./travel/coupling").then((m) => m.coupling),
        bufferstop: () => import("./travel/bufferstop").then((m) => m.bufferStop),
        orderboard: () => import("./travel/orderboard").then((m) => m.orderBoard),
        rowboat: () => import("./travel/rowboat").then((m) => m.rowBoat),
        mooringbuoy: () => import("./travel/mooringbuoy").then((m) => m.mooringBuoy),
    },
    sport: {
        "prop.dice": () => import("./sport/prop.dice").then((m) => m.diceV),
        runners: () => import("./sport/runners").then((m) => m.runners),
        cards: () => import("./sport/cards").then((m) => m.playingCards),
        dominoes: () => import("./sport/dominoes").then((m) => m.dominoes),
        "arcade.sling": () => import("./sport/arcade.sling").then((m) => m.slingFork),
        hoop: () => import("./sport/hoop").then((m) => m.hoop),
        tackle: () => import("./sport/tackle").then((m) => m.tackle),
        die: () => import("./sport/die").then((m) => m.die),
        shutbox: () => import("./sport/shutbox").then((m) => m.shutBox),
        shuttile: () => import("./sport/shuttile").then((m) => m.shutTile),
        goalposts: () => import("./sport/goalposts").then((m) => m.goalposts),
        grandstand: () => import("./sport/grandstand").then((m) => m.grandstand),
        longjump: () => import("./sport/longjump").then((m) => m.longJump),
        medalrow: () => import("./sport/medalrow").then((m) => m.medalRow),
        podium: () => import("./sport/podium").then((m) => m.podium),
        racecar: () => import("./sport/racecar").then((m) => m.raceCar),
        racecircuit: () => import("./sport/racecircuit").then((m) => m.raceCircuit),
        racetrack: () => import("./sport/racetrack").then((m) => m.raceTrack),
        scoreboard: () => import("./sport/scoreboard").then((m) => m.scoreboard),
        target: () => import("./sport/target").then((m) => m.targetBoard),
        teamgrid: () => import("./sport/teamgrid").then((m) => m.teamGrid),
    },
    counting: {
        boxes: () => import("./counting/boxes").then((m) => m.boxesOf),
        "prop.cube": () => import("./counting/prop.cube").then((m) => m.cubeV),
        "prop.ball": () => import("./counting/prop.ball").then((m) => m.ballV),
        "prop.star": () => import("./counting/prop.star").then((m) => m.starV),
        array: () => import("./counting/array").then((m) => m.dotArray),
        barmodel: () => import("./counting/barmodel").then((m) => m.barModel),
        beadstring: () => import("./counting/beadstring").then((m) => m.beadString),
        compare: () => import("./counting/compare").then((m) => m.compareSigns),
        comparebars: () => import("./counting/comparebars").then((m) => m.compareBars),
        fan: () => import("./counting/fan").then((m) => m.numberFan),
        hundred: () => import("./counting/hundred").then((m) => m.hundredSquare),
        inequality: () => import("./counting/inequality").then((m) => m.inequalityLine),
        ladder: () => import("./counting/ladder").then((m) => m.numberLadder),
        nearest: () => import("./counting/nearest").then((m) => m.nearestTo),
        numberball: () => import("./counting/numberball").then((m) => m.numberBall),
        numberbond: () => import("./counting/numberbond").then((m) => m.numberBond),
        numberline: () => import("./counting/numberline").then((m) => m.numberLine),
        ordertrack: () => import("./counting/ordertrack").then((m) => m.orderTrack),
        rekenrek: () => import("./counting/rekenrek").then((m) => m.rekenrek),
        rods: () => import("./counting/rods").then((m) => m.cuisenaire),
        signchain: () => import("./counting/signchain").then((m) => m.signChain),
        sizeorder: () => import("./counting/sizeorder").then((m) => m.sizeOrder),
        tenframe: () => import("./counting/tenframe").then((m) => m.tenFrame),
        towers: () => import("./counting/towers").then((m) => m.cubeTowers),
        tub: () => import("./counting/tub").then((m) => m.counterTub),
        undercup: () => import("./counting/undercup").then((m) => m.underCup),
        washingline: () => import("./counting/washingline").then((m) => m.numberLineRope),
        tally: () => import("./counting/tally").then((m) => m.tallyMarks),
    },
    place: {
        abacus: () => import("./place/abacus").then((m) => m.abacus),
        arrowcards: () => import("./place/arrowcards").then((m) => m.arrowCards),
        baseten: () => import("./place/baseten").then((m) => m.baseTen),
        digitcards: () => import("./place/digitcards").then((m) => m.digitCards),
        gattegno: () => import("./place/gattegno").then((m) => m.gattegno),
        placename: () => import("./place/placename").then((m) => m.placeName),
        placevalue: () => import("./place/placevalue").then((m) => m.placeValue),
        pvchart: () => import("./place/pvchart").then((m) => m.pvChart),
        rounding: () => import("./place/rounding").then((m) => m.roundingLine),
    },
    sums: {
        arrowchain: () => import("./sums/arrowchain").then((m) => m.arrowChain),
        balanceeq: () => import("./sums/balanceeq").then((m) => m.balanceEquation),
        inout: () => import("./sums/inout").then((m) => m.inOutTable),
        letter: () => import("./sums/letter").then((m) => m.letterValue),
        machine: () => import("./sums/machine").then((m) => m.machine),
        machinechain: () => import("./sums/machinechain").then((m) => m.machineChain),
        rulemachine: () => import("./sums/rulemachine").then((m) => m.ruleMachine),
        unknown: () => import("./sums/unknown").then((m) => m.unknownBox),
        areagrid: () => import("./sums/areagrid").then((m) => m.areaGrid),
        longdiv: () => import("./sums/longdiv").then((m) => m.busStop),
        pyramid: () => import("./sums/pyramid").then((m) => m.numberPyramid),
    },
    puzzles: {
        balance: () => import("./puzzles/balance").then((m) => m.balance),
        matchsticks: () => import("./puzzles/matchsticks").then((m) => m.matchsticks),
        pattern: () => import("./puzzles/pattern").then((m) => m.patternStrip),
        sumtriangle: () => import("./puzzles/sumtriangle").then((m) => m.sumTriangle),
        tangram: () => import("./puzzles/tangram").then((m) => m.tangram),
        terms: () => import("./puzzles/terms").then((m) => m.termSequence),
        joindots: () => import("./puzzles/joindots").then((m) => m.joinDots),
    },
    fractions: {
        decimalsquare: () => import("./fractions/decimalsquare").then((m) => m.decimalSquare),
        doubleline: () => import("./fractions/doubleline").then((m) => m.doubleLine),
        equivalent: () => import("./fractions/equivalent").then((m) => m.equivalentBars),
        "fraction.bar": () => import("./fractions/fraction.bar").then((m) => m.fractionBar),
        "fraction.circle": () =>
            import("./fractions/fraction.circle").then((m) => m.fractionCircle),
        fractionwall: () => import("./fractions/fractionwall").then((m) => m.fractionWall),
        mixed: () => import("./fractions/mixed").then((m) => m.mixedNumber),
        percentbar: () => import("./fractions/percentbar").then((m) => m.percentBar),
        pie: () => import("./fractions/pie").then((m) => m.pieChart),
        ratio: () => import("./fractions/ratio").then((m) => m.ratioBars),
    },
    shapes: {
        "prop.shapes": () => import("./shapes/prop.shapes").then((m) => m.shapesV),
        geoboard: () => import("./shapes/geoboard").then((m) => m.geoboard),
        grid: () => import("./shapes/grid").then((m) => m.gridSquares),
        patternblocks: () => import("./shapes/patternblocks").then((m) => m.patternBlocks),
        angle: () => import("./shapes/angle").then((m) => m.angleFig),
        construction: () => import("./shapes/construction").then((m) => m.construction),
        coords: () => import("./shapes/coords").then((m) => m.coordGrid),
        lshape: () => import("./shapes/lshape").then((m) => m.ellShape),
        mirror: () => import("./shapes/mirror").then((m) => m.mirrorShape),
        net: () => import("./shapes/net").then((m) => m.netOfSolid),
        plotpoint: () => import("./shapes/plotpoint").then((m) => m.plotPoint),
        protractor: () => import("./shapes/protractor").then((m) => m.protractor),
        reflect: () => import("./shapes/reflect").then((m) => m.reflectGrid),
        setsquare: () => import("./shapes/setsquare").then((m) => m.setSquare),
        shapemarks: () => import("./shapes/shapemarks").then((m) => m.shapeMarks),
        solid: () => import("./shapes/solid").then((m) => m.solid),
        tessellation: () => import("./shapes/tessellation").then((m) => m.tessellation),
    },
    measuring: {
        containers: () => import("./measuring/containers").then((m) => m.containers),
        dialscale: () => import("./measuring/dialscale").then((m) => m.dialScale),
        jug: () => import("./measuring/jug").then((m) => m.jug),
        masses: () => import("./measuring/masses").then((m) => m.massSet),
        raingauge: () => import("./measuring/raingauge").then((m) => m.rainGauge),
        ruler: () => import("./measuring/ruler").then((m) => m.rulerCm),
        springscale: () => import("./measuring/springscale").then((m) => m.springScale),
        tape: () => import("./measuring/tape").then((m) => m.tapeMeasure),
        thermometer: () => import("./measuring/thermometer").then((m) => m.thermometer),
        tap: () => import("./measuring/tap").then((m) => m.tap),
        catchscale: () => import("./measuring/catchscale").then((m) => m.catchScale),
        scalepole: () => import("./measuring/scalepole").then((m) => m.scalePole),
        riverpost: () => import("./measuring/riverpost").then((m) => m.riverPost),
    },
    money: {
        "prop.coins": () => import("./money/prop.coins").then((m) => m.coinsV),
        change: () => import("./money/change").then((m) => m.changeLine),
        money: () => import("./money/money").then((m) => m.moneyRow),
        pricetag: () => import("./money/pricetag").then((m) => m.priceTag),
        purse: () => import("./money/purse").then((m) => m.purse),
        receipt: () => import("./money/receipt").then((m) => m.receipt),
        shop: () => import("./money/shop").then((m) => m.shopShelf),
        till: () => import("./money/till").then((m) => m.tillDrawer),
        coins: () => import("./money/coins").then((m) => m.coinRow),
        "svg.market-stall": () => import("./imported/svg.market-stall").then((m) => m.marketStall),
        shoveboard: () => import("./money/shoveboard").then((m) => m.shoveBoard),
    },
    time: {
        clock: () => import("./time/clock").then((m) => m.clock),
        calendar: () => import("./time/calendar").then((m) => m.calendarMonth),
        days: () => import("./time/days").then((m) => m.dayStrip),
        digital: () => import("./time/digital").then((m) => m.digitalClock),
        elapsed: () => import("./time/elapsed").then((m) => m.elapsedLine),
        schedule: () => import("./time/schedule").then((m) => m.schedule),
        stopwatch: () => import("./time/stopwatch").then((m) => m.stopwatch),
        sundial: () => import("./time/sundial").then((m) => m.sundial),
        timeline: () => import("./time/timeline").then((m) => m.timeline),
        yearwheel: () => import("./time/yearwheel").then((m) => m.yearWheel),
    },
    data: {
        bag: () => import("./data/bag").then((m) => m.counterBag),
        bargraph: () => import("./data/bargraph").then((m) => m.barGraph),
        carroll: () => import("./data/carroll").then((m) => m.carroll),
        dotplot: () => import("./data/dotplot").then((m) => m.dotPlot),
        linegraph: () => import("./data/linegraph").then((m) => m.lineGraph),
        logicgrid: () => import("./data/logicgrid").then((m) => m.logicGrid),
        picgraph: () => import("./data/picgraph").then((m) => m.pictureGraph),
        probscale: () => import("./data/probscale").then((m) => m.probScale),
        rings: () => import("./data/rings").then((m) => m.sortingRings),
        spinner: () => import("./data/spinner").then((m) => m.spinner),
        table: () => import("./data/table").then((m) => m.dataTable),
        tallytable: () => import("./data/tallytable").then((m) => m.tallyTable),
        venn: () => import("./data/venn").then((m) => m.venn),
        pegboard: () => import("./data/pegboard").then((m) => m.pegBoard),
    },
    letters: {
        alphabet: () => import("./letters/alphabet").then((m) => m.alphabetLine),
        lettercards: () => import("./letters/lettercards").then((m) => m.letterCards),
        match: () => import("./letters/match").then((m) => m.matchPairs),
        sentence: () => import("./letters/sentence").then((m) => m.sentenceStrip),
        soundboxes: () => import("./letters/soundboxes").then((m) => m.soundBoxes),
        soundbuttons: () => import("./letters/soundbuttons").then((m) => m.soundButtons),
        syllables: () => import("./letters/syllables").then((m) => m.syllableArcs),
        wordbricks: () => import("./letters/wordbricks").then((m) => m.wordBricks),
        wordcards: () => import("./letters/wordcards").then((m) => m.wordCards),
        wordladder: () => import("./letters/wordladder").then((m) => m.wordLadder),
        wordscale: () => import("./letters/wordscale").then((m) => m.wordScale),
        wordsort: () => import("./letters/wordsort").then((m) => m.wordSort),
        wordtrain: () => import("./letters/wordtrain").then((m) => m.wordTrain),
    },
    stories: {
        comic: () => import("./stories/comic").then((m) => m.comic),
        picturecards: () => import("./stories/picturecards").then((m) => m.pictureCards),
        postmark: () => import("./stories/postmark").then((m) => m.postmark),
        seaserpent: () => import("./stories/seaserpent").then((m) => m.seaSerpent),
        storymap: () => import("./stories/storymap").then((m) => m.storyMap),
        book: () => import("./stories/book").then((m) => m.bookOpen),
        contents: () => import("./stories/contents").then((m) => m.contents),
        howto: () => import("./stories/howto").then((m) => m.howto),
        labelled: () => import("./stories/labelled").then((m) => m.labelled),
        passage: () => import("./stories/passage").then((m) => m.passage),
        poem: () => import("./stories/poem").then((m) => m.poem),
        postcard: () => import("./stories/postcard").then((m) => m.postcard),
        sequence: () => import("./stories/sequence").then((m) => m.orderRows),
        sign: () => import("./stories/sign").then((m) => m.sign),
    },
    writing: {
        loosepages: () => import("./writing/loosepages").then((m) => m.loosePages),
        acrostic: () => import("./writing/acrostic").then((m) => m.acrostic),
        caption: () => import("./writing/caption").then((m) => m.caption),
        creatures: () => import("./writing/creatures").then((m) => m.creatures),
        expander: () => import("./writing/expander").then((m) => m.expander),
        fixbot: () => import("./writing/fixbot").then((m) => m.fixBot),
        formletter: () => import("./writing/formletter").then((m) => m.formLetter),
        handwriting: () => import("./writing/handwriting").then((m) => m.writingRules),
        letterpage: () => import("./writing/letterpage").then((m) => m.letterPage),
        listpad: () => import("./writing/listpad").then((m) => m.listPad),
        picsteps: () => import("./writing/picsteps").then((m) => m.picSteps),
        storymountain: () => import("./writing/storymountain").then((m) => m.storyMountain),
        treasuremap: () => import("./writing/treasuremap").then((m) => m.treasureMap),
        "word-input": () => import("./writing/word-input").then((m) => m.wordBoxes),
        writingframe: () => import("./writing/writingframe").then((m) => m.writingFrame),
        writinglines: () => import("./writing/writinglines").then((m) => m.writingLines),
    },
    art: {
        weave: () => import("./art/weave").then((m) => m.weave),
        arttools: () => import("./art/arttools").then((m) => m.artTools),
        collage: () => import("./art/collage").then((m) => m.collage),
        colourwheel: () => import("./art/colourwheel").then((m) => m.colourWheel),
        dots: () => import("./art/dots").then((m) => m.dotPicture),
        layers: () => import("./art/layers").then((m) => m.layers),
        linewalk: () => import("./art/linewalk").then((m) => m.lineWalk),
        lines: () => import("./art/lines").then((m) => m.lines),
        mirrorpick: () => import("./art/mirrorpick").then((m) => m.mirrorPick),
        mixingtray: () => import("./art/mixingtray").then((m) => m.mixingTray),
        oneline: () => import("./art/oneline").then((m) => m.oneLine),
        paintbox: () => import("./art/paintbox").then((m) => m.paintBox),
        paintpots: () => import("./art/paintpots").then((m) => m.paintPots),
        paintsheet: () => import("./art/paintsheet").then((m) => m.paintSheet),
        palette: () => import("./art/palette").then((m) => m.palette),
        printrow: () => import("./art/printrow").then((m) => m.printRow),
        radial: () => import("./art/radial").then((m) => m.radial),
        rubbing: () => import("./art/rubbing").then((m) => m.rubbing),
        stamps: () => import("./art/stamps").then((m) => m.stamps),
        stencil: () => import("./art/stencil").then((m) => m.stencil),
        stilllife: () => import("./art/stilllife").then((m) => m.stillLife),
        sunprint: () => import("./art/sunprint").then((m) => m.sunPrint),
        tilerepeat: () => import("./art/tilerepeat").then((m) => m.tileRepeat),
        tintladder: () => import("./art/tintladder").then((m) => m.tintLadder),
        tonescale: () => import("./art/tonescale").then((m) => m.toneScale),
    },
    music: {
        staff: () => import("./music/staff").then((m) => m.rhythmBar),
        beattrack: () => import("./music/beattrack").then((m) => m.beatTrack),
        chimebars: () => import("./music/chimebars").then((m) => m.chimeBars),
        chordbox: () => import("./music/chordbox").then((m) => m.chordBox),
        chordchange: () => import("./music/chordchange").then((m) => m.chordChange),
        countrow: () => import("./music/countrow").then((m) => m.countRow),
        drum: () => import("./music/drum").then((m) => m.drum),
        dynamics: () => import("./music/dynamics").then((m) => m.dynamics),
        fretboard: () => import("./music/fretboard").then((m) => m.fretboard),
        glockenspiel: () => import("./music/glockenspiel").then((m) => m.glockenspiel),
        grandstaff: () => import("./music/grandstaff").then((m) => m.grandStaff),
        guitar: () => import("./music/guitar").then((m) => m.guitar),
        hand: () => import("./music/hand").then((m) => m.hands),
        handdrum: () => import("./music/handdrum").then((m) => m.handDrum),
        lane: () => import("./music/lane").then((m) => m.noteLane),
        notes: () => import("./music/notes").then((m) => m.staffNotes),
        piano: () => import("./music/piano").then((m) => m.pianoKeys),
        strumtrack: () => import("./music/strumtrack").then((m) => m.strumTrack),
        tab: () => import("./music/tab").then((m) => m.tabLines),
        tunegrid: () => import("./music/tunegrid").then((m) => m.tuneGrid),
        ukulele: () => import("./music/ukulele").then((m) => m.ukulele),
    },
    science: {
        bands: () => import("./science/bands").then((m) => m.bands),
        beam: () => import("./science/beam").then((m) => m.beam),
        boat: () => import("./science/boat").then((m) => m.boat),
        chromatography: () => import("./science/chromatography").then((m) => m.chromatography),
        circuit: () => import("./science/circuit").then((m) => m.circuit),
        falling: () => import("./science/falling").then((m) => m.falling),
        forcemeter: () => import("./science/forcemeter").then((m) => m.forcemeter),
        forces: () => import("./science/forces").then((m) => m.forces),
        gears: () => import("./science/gears").then((m) => m.gears),
        globe: () => import("./science/globe").then((m) => m.globe),
        lever: () => import("./science/lever").then((m) => m.lever),
        magnet: () => import("./science/magnet").then((m) => m.magnet),
        microscope: () => import("./science/microscope").then((m) => m.microscope),
        mirrors: () => import("./science/mirrors").then((m) => m.mirrors),
        moonphases: () => import("./science/moonphases").then((m) => m.moonphases),
        orbit: () => import("./science/orbit").then((m) => m.orbit),
        parachute: () => import("./science/parachute").then((m) => m.parachute),
        pendulum: () => import("./science/pendulum").then((m) => m.pendulum),
        periscope: () => import("./science/periscope").then((m) => m.periscope),
        planets: () => import("./science/planets").then((m) => m.planets),
        prism: () => import("./science/prism").then((m) => m.prism),
        pulley: () => import("./science/pulley").then((m) => m.pulley),
        ramp: () => import("./science/ramp").then((m) => m.ramp),
        ricedrum: () => import("./science/ricedrum").then((m) => m.ricedrum),
        seeing: () => import("./science/seeing").then((m) => m.seeing),
        seesaw: () => import("./science/seesaw").then((m) => m.seesaw),
        series: () => import("./science/series").then((m) => m.series),
        shadows: () => import("./science/shadows").then((m) => m.shadows),
        stringphone: () => import("./science/stringphone").then((m) => m.stringPhone),
        sunpath: () => import("./science/sunpath").then((m) => m.sunpath),
        tank: () => import("./science/tank").then((m) => m.tank),
        telescope: () => import("./science/telescope").then((m) => m.telescope),
        tester: () => import("./science/tester").then((m) => m.tester),
        things: () => import("./science/things").then((m) => m.things),
        turbine: () => import("./science/turbine").then((m) => m.turbine),
        weatherstation: () => import("./science/weatherstation").then((m) => m.weatherStation),
        wheelaxle: () => import("./science/wheelaxle").then((m) => m.wheelAxle),
        wrapped: () => import("./science/wrapped").then((m) => m.wrapped),
        atombox: () => import("./science/atombox").then((m) => m.atombox),
        beaker: () => import("./science/beaker").then((m) => m.beaker),
        beforeafter: () => import("./science/beforeafter").then((m) => m.beforeAfter),
        cabbage: () => import("./science/cabbage").then((m) => m.cabbage),
        candle: () => import("./science/candle").then((m) => m.candle),
        condense: () => import("./science/condense").then((m) => m.condense),
        crystalstring: () => import("./science/crystalstring").then((m) => m.crystalstring),
        cylinder: () => import("./science/cylinder").then((m) => m.cylinder),
        dish: () => import("./science/dish").then((m) => m.dish),
        dropper: () => import("./science/dropper").then((m) => m.dropper),
        fizz: () => import("./science/fizz").then((m) => m.fizz),
        flame: () => import("./science/flame").then((m) => m.flame),
        flask: () => import("./science/flask").then((m) => m.flask),
        fossilsteps: () => import("./science/fossilsteps").then((m) => m.fossilsteps),
        funnel: () => import("./science/funnel").then((m) => m.funnel),
        heatcurve: () => import("./science/heatcurve").then((m) => m.heatcurve),
        icemelt: () => import("./science/icemelt").then((m) => m.icemelt),
        magnifier: () => import("./science/magnifier").then((m) => m.magnifier),
        materials: () => import("./science/materials").then((m) => m.materials),
        mixture: () => import("./science/mixture").then((m) => m.mixture),
        molecule: () => import("./science/molecule").then((m) => m.molecule),
        nails: () => import("./science/nails").then((m) => m.nails),
        particles: () => import("./science/particles").then((m) => m.particles),
        rocks: () => import("./science/rocks").then((m) => m.rocks),
        safety: () => import("./science/safety").then((m) => m.safety),
        sieve: () => import("./science/sieve").then((m) => m.sieve),
        soiljar: () => import("./science/soiljar").then((m) => m.soiljar),
        squash: () => import("./science/squash").then((m) => m.squash),
        testtubes: () => import("./science/testtubes").then((m) => m.testtubes),
        watercycle: () => import("./science/watercycle").then((m) => m.watercycle),
        parts: () => import("./science/parts").then((m) => m.partsDiagram),
        crane: () => import("./science/crane").then((m) => m.crane),
        fulcrum: () => import("./science/fulcrum").then((m) => m.fulcrum),
        seesawplank: () => import("./science/seesawplank").then((m) => m.seesawPlank),
        seesawprops: () => import("./science/seesawprops").then((m) => m.seesawProps),
    },
    coding: {
        blocks: () => import("./coding/blocks").then((m) => m.blocks),
        blocktray: () => import("./coding/blocktray").then((m) => m.blockTray),
        codepad: () => import("./coding/codepad").then((m) => m.codePad),
        cups: () => import("./coding/cups").then((m) => m.cups),
        dance: () => import("./coding/dance").then((m) => m.dance),
        fork: () => import("./coding/fork").then((m) => m.fork),
        lamps: () => import("./coding/lamps").then((m) => m.lamps),
        maze: () => import("./coding/maze").then((m) => m.maze),
        pixels: () => import("./coding/pixels").then((m) => m.pixels),
        program: () => import("./coding/program").then((m) => m.program),
        sortcards: () => import("./coding/sortcards").then((m) => m.sortCards),
        sortnet: () => import("./coding/sortnet").then((m) => m.sortNet),
        stage: () => import("./coding/stage").then((m) => m.stage),
        tracetable: () => import("./coding/tracetable").then((m) => m.traceTable),
        tune: () => import("./coding/tune").then((m) => m.tune),
        turtle: () => import("./coding/turtle").then((m) => m.turtle),
        variable: () => import("./coding/variable").then((m) => m.variable),
    },
    page: {
        starrow: () => import("./page/starrow").then((m) => m.starRow),
        bubble: () => import("./page/bubble").then((m) => m.speechBubble),
        note: () => import("./page/note").then((m) => m.noteCard),
        dayloop: () => import("./page/dayloop").then((m) => m.dayLoop),
        stickers: () => import("./page/stickers").then((m) => m.stickers),
        callout: () => import("./page/callout").then((m) => m.callout),
        divider: () => import("./page/divider").then((m) => m.divider),
        pinned: () => import("./page/pinned").then((m) => m.pinnedCard),
        steps: () => import("./page/steps").then((m) => m.stepDots),
        choice: () => import("./page/choice").then((m) => m.choiceCards),
        "arcade.puff": () => import("./page/arcade.puff").then((m) => m.puff),
        "fx.sparkle": () => import("./page/fx.sparkle").then((m) => m.sparkle),
        "fx.drop": () => import("./page/fx.drop").then((m) => m.drop),
    },
    apps: {
        icon: () => import("./apps/icon").then((m) => m.icon),
        newbook: () => import("./apps/newbook").then((m) => m.newbook),
        grownup: () => import("./apps/grownup").then((m) => m.grownup),
    },
    guide: {
        "guide.firefly": () => import("./guide/guide.firefly").then((m) => m.guideV),
        "guide.glow": () => import("./guide/guide.glow").then((m) => m.guideGlow),
        "guide.hand": () => import("./guide/guide.hand").then((m) => m.guideHand),
        "guide.stub": () => import("./guide/guide.stub").then((m) => m.guideStub),
        "guide.bird": () => import("./guide/guide.bird").then((m) => m.guideBird),
        "guide.snail": () => import("./guide/guide.snail").then((m) => m.guideSnail),
        "guide.dot": () => import("./guide/guide.dot").then((m) => m.guideDot),
    },
} as const;

type Loader = () => Promise<Drawing<unknown>>;

// Checked by assignment rather than `satisfies`, which would widen every loader's drawing to unknown.
const LINES: Partial<Record<Family, Readonly<Record<string, Loader>>>> = CATALOG;

type Catalog = typeof CATALOG;

export type Id = { [F in keyof Catalog]: keyof Catalog[F] & string }[keyof Catalog];

type Loads<T, K extends string> = T extends Record<K, () => Promise<infer D>> ? D : never;

export type ParamsOf<K extends Id> =
    Loads<Catalog[keyof Catalog], K> extends Drawing<infer P> ? P : never;

/** A hand-drawn file's drawing, which the worlds and the pictures name as `file:` and the file's name (artKey in engine/space.ts). */
const HAND_DRAWN = /^(?:svg|excalidraw|strokes)\./;

const FILED: ReadonlyMap<string, Loader> = new Map(
    Object.values(LINES).flatMap((family) =>
        Object.entries(family ?? {}).flatMap(([id, load]): [string, Loader][] =>
            HAND_DRAWN.test(id)
                ? [
                      [id, load],
                      [`file:${id.replace(HAND_DRAWN, "")}`, load],
                  ]
                : [[id, load]],
        ),
    ),
);

/** The loader for a drawing, by its id or a hand-drawn file's `file:` name, or undefined for neither. */
export const loaderOf = (id: string): Loader | undefined => FILED.get(id);
