// Where each drawing is found and what a parent searches for it by: the shelves in the order the
// studio shows them, the ideas a drawing can show, and each moved drawing's placement. Only the
// studio and search load this file; a page that draws a drawing never does.

/** The shelves, in the order the page shows them. `band` is the heading a run of shelves sits under. */
export const SHELVES = [
    {
        id: "animals",
        band: "Things",
        name: "Animals",
        blurb: "Pets, farm animals, minibeasts and the creatures of the worlds, to count, compare and write about.",
    },
    {
        id: "people",
        band: "Things",
        name: "People and feelings",
        blurb: "Children to share things between, a row of heads to count along, and a face that shows how someone feels.",
    },
    {
        id: "food",
        band: "Things",
        name: "Food and the kitchen",
        blurb: "Where fractions and capacity live at home: a pizza to cut, eggs in a box, a jug to fill and a table laid for a birthday.",
    },
    {
        id: "home",
        band: "Things",
        name: "At home and at play",
        blurb: "Mugs, pencils, a shelf, a kite and the bunting: ordinary things a question can be about.",
    },
    {
        id: "outdoors",
        band: "Things",
        name: "Outdoors and nature",
        blurb: "Trees through the year, flowers, the pond, the sky at night and the land from hills to icebergs.",
    },
    {
        id: "places",
        band: "Things",
        name: "Buildings and places",
        blurb: "Houses, a lighthouse, a station, a clock tower, a windmill and a bridge: somewhere for a story to happen.",
    },
    {
        id: "travel",
        band: "Things",
        name: "Getting about and maps",
        blurb: "Buses, trains, boats and bicycles, the tickets and timetables that go with them, and maps to find the way.",
    },
    {
        id: "sport",
        band: "Things",
        name: "Sport and games",
        blurb: "Tracks, scores, targets and medals, and the dice, dominoes and cards a game is played with.",
    },
    {
        id: "counting",
        band: "Maths",
        name: "Counting and number",
        blurb: "The things a child reads a number off: ten frames, bonds, lines, rods, beads and counters, and the signs for bigger and smaller.",
    },
    {
        id: "place",
        band: "Maths",
        name: "Tens and ones",
        blurb: "Which column a digit sits in and what it is worth: blocks, charts, arrow cards and the line a number is rounded along.",
    },
    {
        id: "sums",
        band: "Maths",
        name: "Sums and missing numbers",
        blurb: "Layouts a child writes a sum into, machines that apply a rule, and a box or a letter for the number not known yet.",
    },
    {
        id: "puzzles",
        band: "Maths",
        name: "Puzzles and patterns",
        blurb: "Pictures that hold a question: what balances, what comes next, which stick to move.",
    },
    {
        id: "fractions",
        band: "Maths",
        name: "Fractions, decimals and percent",
        blurb: "Halves, quarters and thirds, the fraction wall, tenths and hundredths, and percent on a bar.",
    },
    {
        id: "shapes",
        band: "Maths",
        name: "Shapes, angles and space",
        blurb: "Flat and solid shapes, nets, angles and the tools that measure them, mirror lines and coordinates.",
    },
    {
        id: "measuring",
        band: "Maths",
        name: "Measuring",
        blurb: "Rulers and tapes at life size, scales, jugs and thermometers, each with the marks a question is about.",
    },
    {
        id: "money",
        band: "Maths",
        name: "Money and shopping",
        blurb: "Coins at their real sizes, notes, a purse, price tags, a receipt and the till.",
    },
    {
        id: "time",
        band: "Maths",
        name: "Time and the calendar",
        blurb: "Clock faces and readouts, a month, a week and a year, and the line elapsed time is counted along.",
    },
    {
        id: "data",
        band: "Maths",
        name: "Charts, sorting and chance",
        blurb: "Tallies, tables and graphs, the rings and diagrams things are sorted into, and how likely the next one is.",
    },
    {
        id: "letters",
        band: "Subjects",
        name: "Letters, sounds and words",
        blurb: "Letter cards, sound buttons, syllables and words handled one to a cell, the way the maths drawings handle numbers.",
    },
    {
        id: "stories",
        band: "Subjects",
        name: "Stories and things to read",
        blurb: "Passages, poems, signs, postcards and comics, and pictures a reading question can ask about.",
    },
    {
        id: "writing",
        band: "Subjects",
        name: "Writing",
        blurb: "Ruled lines, handwriting rows, boxes for a word and frames to plan a piece of writing in.",
    },
    {
        id: "art",
        band: "Subjects",
        name: "Art and painting",
        blurb: "Paint that mixes like paint, the paint box and the tools, the colour wheel, tints and shades, print blocks, patterns and their mirrors, and the sheet an art lesson is painted on.",
    },
    {
        id: "music",
        band: "Subjects",
        name: "Music",
        blurb: "A keyboard and a ukulele or guitar that play, notes on a staff and the grand staff, chord boxes, tab and strum arrows, and the track a rhythm is clapped along.",
    },
    {
        id: "science",
        band: "Subjects",
        name: "Science",
        blurb: "Beakers and burners, magnets, circuits, ramps and see-saws: apparatus drawn so a reading can be taken off it.",
    },
    {
        id: "coding",
        band: "Subjects",
        name: "Coding",
        blurb: "Programs as blocks and as lines, and the worlds they run in: a robot in a maze, a turtle's pen, pixel art, a stage, a dance and a tune, with the pieces for names, decisions, sorting and binary.",
    },
    {
        id: "page",
        band: "The page",
        name: "Notes, stickers and answer boxes",
        blurb: "What sits around a question: the guide and what it says, the teacher's pen, the choices a child picks from, and rewards.",
    },
    {
        id: "apps",
        band: "The apps",
        name: "The apps' own drawings",
        blurb: "The icons on the apps' own controls, and the pictures an empty page, a first visit and a finished day show, drawn as one set so the apps read as one hand.",
    },
] as const;

export type ShelfId = (typeof SHELVES)[number]["id"];

/**
 * What a drawing can show, in the words a parent searches with. `words` are matched as well as the
 * name, so "half", "quarter" and "fraction" all find the pizza.
 */
export const IDEAS = {
    counting: { name: "Counting", words: "count how many one more fewer" },
    adding: {
        name: "Adding and taking away",
        words: "add plus sum total more take away subtract minus left difference",
    },
    bonds: { name: "Number bonds", words: "bond make ten pairs part whole" },
    times: {
        name: "Times tables and equal groups",
        words: "times multiply multiplication groups rows array twos fives tens lots each",
    },
    sharing: {
        name: "Sharing and dividing",
        words: "share divide division each left over remainder",
    },
    halves: {
        name: "Halves, quarters and fractions",
        words: "half quarter third fraction equal parts slice shaded whole",
    },
    decimals: { name: "Decimals and percent", words: "decimal tenth hundredth percent point" },
    place: {
        name: "Tens, hundreds and place value",
        words: "tens ones hundreds thousands digit column exchange round rounding",
    },
    ordering: {
        name: "Bigger, smaller and in order",
        words: "compare bigger smaller greater less order largest smallest tallest shortest first last",
    },
    patterns: {
        name: "Patterns and sequences",
        words: "pattern next repeat sequence rule growing",
    },
    puzzles: {
        name: "Puzzles and reasoning",
        words: "puzzle logic reasoning missing unknown equation algebra think",
    },
    shape: {
        name: "Shapes",
        words: "shape triangle square circle hexagon rectangle solid net sides corners faces edges 2d 3d",
    },
    symmetry: {
        name: "Angles, turns and symmetry",
        words: "angle degrees right angle turn rotate mirror reflect symmetry line",
    },
    position: {
        name: "Position and maps",
        words: "map grid reference coordinates route directions north south east west left right where",
    },
    length: {
        name: "Length and distance",
        words: "length long tall height centimetre cm metre km distance ruler measure far",
    },
    weight: {
        name: "Weight and mass",
        words: "weight mass heavy light gram kilogram kg scales weigh",
    },
    capacity: {
        name: "Capacity and volume",
        words: "capacity volume litre millilitre ml pour full empty",
    },
    temperature: { name: "Temperature", words: "temperature hot cold degrees warm freezing" },
    time: {
        name: "Telling the time",
        words: "time clock o'clock half past quarter minute hour second",
    },
    calendar: {
        name: "Days, months and seasons",
        words: "day week month year calendar season date birthday",
    },
    money: {
        name: "Money and shopping",
        words: "money coin cents dollar price cost change pay buy shop spend",
    },
    data: { name: "Charts and tables", words: "chart graph table tally data survey pictogram" },
    chance: {
        name: "Sorting and chance",
        words: "sort sorting group venn carroll chance likely probability",
    },
    letters: {
        name: "Letters and sounds",
        words: "letter sound phonics alphabet spell spelling syllable blend",
    },
    words: {
        name: "Words and sentences",
        words: "word sentence grammar punctuation capital comma noun verb adjective meaning",
    },
    reading: {
        name: "Reading and stories",
        words: "read reading story passage book poem character clue",
    },
    writing: { name: "Writing and handwriting", words: "write writing handwriting lines plan" },
    colour: {
        name: "Colour and painting",
        words: "colour color paint painting mix mixing primary secondary tint shade warm cool wheel brush crayon print stamp art draw drawing",
    },
    music: {
        name: "Music",
        words: "music note rhythm beat piano keyboard song staff guitar ukulele uke chord strum",
    },
    science: {
        name: "Science",
        words: "science experiment materials forces push pull magnet circuit float sink light shadow solid liquid gas",
    },
    nature: {
        name: "Nature and living things",
        words: "nature animal plant tree flower insect bird season living grow",
    },
    coding: {
        name: "Coding and instructions",
        words: "code coding program instructions robot algorithm bug repeat",
    },
    rewards: { name: "Praise and progress", words: "reward sticker well done star progress prize" },
} as const;

export type IdeaId = keyof typeof IDEAS;

export interface Placement {
    /** The shelf it lives on. */
    on: ShelfId;
    /** Other shelves it is also found on: a pizza is food, and it is also a fraction. */
    also: ShelfId[];
    shows: IdeaId[];
    /** More words it answers to, where the title and the description do not say them. */
    words: string;
}

/** Every drawing in engine/parts, by its id: where it is found, and the words it answers to. */
export const GROUPING: Readonly<Record<string, Placement>> = {
    beattrack: { on: "music", also: [], shows: ["music"], words: "clap rhythm" },
    chimebars: {
        on: "music",
        also: [],
        shows: ["music", "ordering"],
        words: "chime bars glockenspiel xylophone scale high low",
    },
    chordbox: {
        on: "music",
        also: [],
        shows: ["music"],
        words: "guitar ukulele uke chord diagram fingers",
    },
    chordchange: {
        on: "music",
        also: [],
        shows: ["music"],
        words: "guitar ukulele uke chord change fingers move",
    },
    countrow: {
        on: "music",
        also: [],
        shows: ["music", "counting"],
        words: "count beat beats bar metronome keep the beat tap words",
    },
    drum: {
        on: "music",
        also: [],
        shows: ["music", "counting"],
        words: "drum beat sticks rhythm band",
    },
    dynamics: {
        on: "music",
        also: [],
        shows: ["music"],
        words: "loud soft piano forte crescendo diminuendo",
    },
    fretboard: {
        on: "music",
        also: [],
        shows: ["music"],
        words: "guitar ukulele uke strings neck fret frets play",
    },
    glockenspiel: {
        on: "music",
        also: [],
        shows: ["music", "ordering"],
        words: "glockenspiel xylophone bars mallet beater metal play notes high low scale",
    },
    grandstaff: {
        on: "music",
        also: [],
        shows: ["music"],
        words: "piano grand staff treble bass clef middle c landmark",
    },
    guitar: {
        on: "music",
        also: [],
        shows: ["music"],
        words: "guitar instrument strings parts head pegs neck frets body sound hole bridge",
    },
    hand: {
        on: "music",
        also: ["people"],
        shows: ["music", "counting"],
        words: "hand hands fingers finger numbers thumb piano guitar",
    },
    handdrum: {
        on: "music",
        also: [],
        shows: ["music", "counting"],
        words: "drum hand drum djembe beat rhythm hit tap dum ta echo",
    },
    lane: {
        on: "music",
        also: [],
        shows: ["music"],
        words: "guitar ukulele uke play along notes coming lane",
    },
    notes: { on: "music", also: [], shows: ["music"], words: "staff treble" },
    piano: { on: "music", also: [], shows: ["music"], words: "" },
    strumtrack: {
        on: "music",
        also: [],
        shows: ["music", "counting"],
        words: "guitar ukulele uke strum strumming pattern down up rhythm",
    },
    tab: {
        on: "music",
        also: [],
        shows: ["music"],
        words: "guitar ukulele uke tablature tab frets strings read",
    },
    tunegrid: {
        on: "music",
        also: [],
        shows: ["music"],
        words: "tune compose make up write notes grid glockenspiel pentatonic",
    },
    ukulele: {
        on: "music",
        also: [],
        shows: ["music"],
        words: "ukulele uke instrument strings parts head pegs neck frets body sound hole bridge",
    },
    blocks: {
        on: "coding",
        also: [],
        shows: ["coding"],
        words: "blocks scratch loop repeat if when event flag",
    },
    blocktray: { on: "coding", also: [], shows: ["coding"], words: "blocks palette choose" },
    codepad: {
        on: "coding",
        also: [],
        shows: ["coding", "writing"],
        words: "write program blocks slots answer",
    },
    cups: {
        on: "coding",
        also: [],
        shows: ["coding", "ordering"],
        words: "search searching binary guess halve",
    },
    dance: {
        on: "coding",
        also: [],
        shows: ["coding", "music"],
        words: "dance moves clap jump spin",
    },
    fork: {
        on: "coding",
        also: [],
        shows: ["coding", "puzzles"],
        words: "if decision condition yes no choice",
    },
    lamps: {
        on: "coding",
        also: [],
        shows: ["coding", "place"],
        words: "binary lamps bits on off",
    },
    maze: {
        on: "coding",
        also: ["travel"],
        shows: ["coding", "position"],
        words: "robot maze gem flag rocks path route",
    },
    pixels: {
        on: "coding",
        also: ["shapes"],
        shows: ["coding", "patterns"],
        words: "pixel picture colour squares art",
    },
    program: {
        on: "coding",
        also: [],
        shows: ["coding"],
        words: "listing lines code bug debug loop",
    },
    sortcards: {
        on: "coding",
        also: [],
        shows: ["coding", "ordering"],
        words: "sort sorting swap algorithm",
    },
    sortnet: {
        on: "coding",
        also: [],
        shows: ["coding", "ordering"],
        words: "sorting network algorithm",
    },
    stage: {
        on: "coding",
        also: ["stories"],
        shows: ["coding", "reading"],
        words: "stage story animation event flag rabbit crab",
    },
    tracetable: { on: "coding", also: [], shows: ["coding", "data"], words: "trace table steps" },
    tune: {
        on: "coding",
        also: ["music"],
        shows: ["coding", "music"],
        words: "tune notes chime bars glockenspiel play",
    },
    turtle: {
        on: "coding",
        also: [],
        shows: ["coding", "position", "shape"],
        words: "pen draw square path",
    },
    variable: {
        on: "coding",
        also: [],
        shows: ["coding", "puzzles"],
        words: "variable name box number changes",
    },
    acrostic: { on: "writing", also: [], shows: ["writing"], words: "poem" },
    alphabet: { on: "letters", also: [], shows: ["letters", "ordering"], words: "" },
    book: { on: "stories", also: [], shows: ["reading", "writing"], words: "" },
    caption: { on: "writing", also: [], shows: ["writing"], words: "label picture" },
    contents: { on: "stories", also: [], shows: ["reading"], words: "contents page book" },
    creatures: {
        on: "writing",
        also: ["animals"],
        shows: ["words", "writing"],
        words: "monsters describe eyes legs",
    },
    expander: {
        on: "writing",
        also: [],
        shows: ["writing", "words"],
        words: "sentence when where why how",
    },
    fixbot: {
        on: "writing",
        also: ["coding"],
        shows: ["words", "writing"],
        words: "robot mistake fix sentence",
    },
    formletter: {
        on: "writing",
        also: [],
        shows: ["writing", "letters"],
        words: "letter formation strokes trace",
    },
    gridmap: { on: "travel", also: [], shows: ["position"], words: "map grid reference island" },
    handwriting: { on: "writing", also: [], shows: ["writing"], words: "" },
    howto: {
        on: "stories",
        also: ["writing"],
        shows: ["reading", "writing"],
        words: "instructions steps recipe",
    },
    labelled: {
        on: "stories",
        also: ["science"],
        shows: ["reading", "science"],
        words: "diagram labels",
    },
    lettercards: { on: "letters", also: [], shows: ["letters"], words: "" },
    letterpage: { on: "writing", also: [], shows: ["writing"], words: "letter envelope dear" },
    listpad: { on: "writing", also: [], shows: ["writing"], words: "list notepad shopping" },
    match: { on: "letters", also: [], shows: ["words", "reading"], words: "pairs join" },
    parts: {
        on: "science",
        also: [],
        shows: ["science", "reading"],
        words: "plant fish island label",
    },
    passage: { on: "stories", also: [], shows: ["reading"], words: "" },
    picsteps: {
        on: "writing",
        also: [],
        shows: ["writing", "ordering"],
        words: "instructions steps order",
    },
    poem: { on: "stories", also: [], shows: ["reading"], words: "rhyme verse" },
    postcard: {
        on: "stories",
        also: ["writing"],
        shows: ["reading", "writing"],
        words: "letter holiday",
    },
    sentence: { on: "letters", also: [], shows: ["words", "reading"], words: "gap fill blank" },
    sequence: {
        on: "stories",
        also: [],
        shows: ["reading", "ordering"],
        words: "order steps first next",
    },
    sign: { on: "stories", also: [], shows: ["reading"], words: "notice bus stop" },
    soundboxes: { on: "letters", also: [], shows: ["letters"], words: "" },
    soundbuttons: { on: "letters", also: [], shows: ["letters"], words: "" },
    staff: { on: "music", also: [], shows: ["music"], words: "rhythm bar" },
    storymountain: {
        on: "writing",
        also: ["stories"],
        shows: ["writing", "reading"],
        words: "story plan beginning middle end",
    },
    syllables: { on: "letters", also: [], shows: ["letters"], words: "" },
    treasuremap: {
        on: "writing",
        also: ["travel"],
        shows: ["writing", "position"],
        words: "map directions pirate route",
    },
    "word-input": {
        on: "writing",
        also: [],
        shows: ["letters", "writing"],
        words: "spelling boxes answer",
    },
    wordbricks: { on: "letters", also: [], shows: ["words"], words: "" },
    wordcards: { on: "letters", also: [], shows: ["words"], words: "" },
    wordladder: { on: "letters", also: [], shows: ["letters", "words"], words: "" },
    wordscale: { on: "letters", also: [], shows: ["words"], words: "shades of meaning" },
    wordsort: { on: "letters", also: [], shows: ["words"], words: "columns sort" },
    wordtrain: { on: "letters", also: [], shows: ["words"], words: "" },
    writingframe: { on: "writing", also: [], shows: ["writing"], words: "plan boxes" },
    writinglines: { on: "writing", also: [], shows: ["writing"], words: "" },
    bands: {
        on: "science",
        also: ["music"],
        shows: ["science", "music"],
        words: "sound pitch high low string band elastic pluck vibrate vibration loud quiet length",
    },
    beam: {
        on: "science",
        also: [],
        shows: ["science"],
        words: "light torch shadow transparent translucent opaque glass paper card see through",
    },
    boat: {
        on: "science",
        also: [],
        shows: ["science", "counting"],
        words: "boat float sink upthrust water push load blocks cargo",
    },
    circuit: {
        on: "science",
        also: [],
        shows: ["science"],
        words: "bulb battery switch electricity",
    },
    chromatography: {
        on: "science",
        also: ["art"],
        shows: ["science", "colour"],
        words: "chromatography ink pen colours separate mixture paper strip filter water",
    },
    forcemeter: {
        on: "science",
        also: ["measuring"],
        shows: ["science", "weight"],
        words: "force meter newton meter newtons friction surface pull spring shoe ice wood carpet sandpaper grip",
    },
    forces: { on: "science", also: [], shows: ["science"], words: "arrows newtons" },
    gears: {
        on: "science",
        also: ["puzzles"],
        shows: ["science", "times"],
        words: "gear gears teeth turn clockwise anticlockwise ratio simple machine cog",
    },
    globe: {
        on: "science",
        also: ["outdoors"],
        shows: ["science", "time"],
        words: "earth day night turn spin rotate sun globe world time zone space",
    },
    lever: {
        on: "science",
        also: ["puzzles"],
        shows: ["science", "weight"],
        words: "lever pivot fulcrum machine push lift crowbar simple machine turning",
    },
    magnet: {
        on: "science",
        also: [],
        shows: ["science"],
        words: "magnetic poles paperclip chain strength how strong pull distance fair test",
    },
    microscope: {
        on: "science",
        also: [],
        shows: ["science", "nature"],
        words: "microscope lens magnify eyepiece stage slide mirror lamp focus cells laboratory lab",
    },
    mirrors: {
        on: "science",
        also: ["puzzles"],
        shows: ["science", "position"],
        words: "light mirror mirrors reflect reflection ray beam torch maze bounce",
    },
    moonphases: {
        on: "science",
        also: ["outdoors"],
        shows: ["science", "calendar"],
        words: "moon phases month crescent half full new gibbous night sky space",
    },
    orbit: {
        on: "science",
        also: ["outdoors"],
        shows: ["science", "calendar"],
        words: "earth moon sun orbit phases day night above pole space",
    },
    parachute: {
        on: "science",
        also: [],
        shows: ["science"],
        words: "parachute air resistance falling gravity weight drag canopy steady speed",
    },
    falling: {
        on: "science",
        also: [],
        shows: ["science", "ordering"],
        words: "fall drop air resistance leaf feather stone parachute paper crumpled which lands first",
    },
    pendulum: {
        on: "science",
        also: [],
        shows: ["science", "length", "time"],
        words: "pendulum swing string bob length fair test time",
    },
    periscope: {
        on: "science",
        also: [],
        shows: ["science"],
        words: "light mirror mirrors periscope reflect see over wall ray",
    },
    planets: {
        on: "science",
        also: ["outdoors"],
        shows: ["ordering", "length"],
        words: "planets space sun solar system mercury venus earth mars jupiter saturn uranus neptune",
    },
    prism: {
        on: "science",
        also: [],
        shows: ["science", "ordering"],
        words: "light prism rainbow colours spectrum red orange yellow green blue indigo violet white light",
    },
    pulley: {
        on: "science",
        also: [],
        shows: ["science", "weight"],
        words: "pulley pulleys rope lift crane simple machine block and tackle",
    },
    ramp: {
        on: "science",
        also: [],
        shows: ["science", "length"],
        words: "slope roll ball marble track cup push energy height steeper",
    },
    "workshop-piece": {
        on: "science",
        also: [],
        shows: ["science", "weight"],
        words: "workshop crate ramp marble boat crane hook cargo construction",
    },
    ricedrum: {
        on: "science",
        also: [],
        shows: ["science", "music"],
        words: "sound drum rice vibrate vibration loud quiet hit shake",
    },
    seeing: {
        on: "science",
        also: [],
        shows: ["science"],
        words: "light see seeing eye lamp dark how we see reflect",
    },
    seesaw: {
        on: "science",
        also: ["puzzles"],
        shows: ["science", "weight"],
        words: "balance lever",
    },
    series: {
        on: "science",
        also: [],
        shows: ["science"],
        words: "circuit bulb bulbs battery cell cells switch buzzer motor brighter dimmer electricity loose wire",
    },
    shadows: { on: "science", also: [], shows: ["science", "length"], words: "shadow sun lamp" },
    stringphone: {
        on: "science",
        also: ["people"],
        shows: ["science"],
        words: "sound string telephone cups vibration hear ear knock table water travel",
    },
    sunpath: {
        on: "science",
        also: ["outdoors"],
        shows: ["science", "time", "calendar"],
        words: "sun sunrise sunset day length summer winter seasons sky path",
    },
    tank: { on: "science", also: [], shows: ["science"], words: "float sink water" },
    telescope: { on: "science", also: [], shows: ["symmetry"], words: "stars space" },
    tester: {
        on: "science",
        also: [],
        shows: ["science"],
        words: "circuit conductor insulator metal electricity bulb gap test material",
    },
    things: {
        on: "science",
        also: [],
        shows: ["science", "chance"],
        words: "materials metal plastic wood glass rubber magnet magnetic conductor light source candle torch moon mirror sort",
    },
    turbine: {
        on: "science",
        also: ["outdoors"],
        shows: ["science"],
        words: "wind turbine energy electricity lamps house blades renewable",
    },
    weatherstation: {
        on: "science",
        also: ["measuring", "outdoors"],
        shows: ["temperature", "data"],
        words: "weather station wind vane anemometer rain gauge thermometer compass",
    },
    wheelaxle: {
        on: "science",
        also: [],
        shows: ["science", "weight"],
        words: "wheel axle winch lever simple machine rope lift",
    },
    wrapped: {
        on: "science",
        also: ["measuring"],
        shows: ["science", "temperature"],
        words: "heat warm cool insulator insulation wrap wool cup hot water thermometer keep warm fair test ice cold melt foil cloth",
    },
    atombox: {
        on: "science",
        also: [],
        shows: ["science", "counting"],
        words: "atoms molecules box gas pure substance mixture element compound model chemistry",
    },
    beaker: {
        on: "science",
        also: ["measuring"],
        shows: ["capacity", "science"],
        words: "chemistry",
    },
    beforeafter: {
        on: "science",
        also: ["food"],
        shows: ["science", "ordering"],
        words: "change reversible irreversible undo melt freeze boil dissolve toast bake cook egg candle burn rust fizz dough before after new material chemistry",
    },
    cabbage: {
        on: "science",
        also: [],
        shows: ["science", "colour"],
        words: "red cabbage indicator acid alkali neutral ph colour chart lemon vinegar baking soda washing soda chemistry",
    },
    candle: {
        on: "science",
        also: ["home"],
        shows: ["science", "length"],
        words: "candle burning wax cm ruler burnt jar air flame out chemistry",
    },
    condense: {
        on: "science",
        also: [],
        shows: ["science"],
        words: "condense condensation drops cold glass ice lid steam water vapour air chemistry",
    },
    crystalstring: {
        on: "science",
        also: [],
        shows: ["science", "counting", "time"],
        words: "crystals grow string salt sugar jar evaporate days chemistry",
    },
    cylinder: {
        on: "science",
        also: ["measuring"],
        shows: ["capacity", "science"],
        words: "measuring cylinder millilitres ml scale meniscus read volume liquid chemistry",
    },
    dish: {
        on: "science",
        also: [],
        shows: ["science", "time"],
        words: "evaporating dish salt water crust windowsill days evaporate chemistry",
    },
    dropper: {
        on: "science",
        also: [],
        shows: ["science", "counting"],
        words: "dropper pipette drops indicator chemistry",
    },
    fizz: {
        on: "science",
        also: ["food"],
        shows: ["science"],
        words: "fizz baking soda bicarbonate vinegar foam bubbles pop reaction gas carbon dioxide volcano chemistry",
    },
    flame: { on: "science", also: [], shows: ["science"], words: "burner heat" },
    flask: {
        on: "science",
        also: [],
        shows: ["science", "capacity"],
        words: "flask conical round balloon stopper bubbles gas reaction chemistry",
    },
    fossilsteps: {
        on: "science",
        also: ["outdoors"],
        shows: ["science", "ordering"],
        words: "fossil forms ammonite sea mud layers rock millions of years found cliff steps order chemistry",
    },
    funnel: { on: "science", also: [], shows: ["science"], words: "filter separate" },
    heatcurve: {
        on: "science",
        also: ["data"],
        shows: ["temperature", "data", "science"],
        words: "heating curve temperature graph minutes boiling melting flat thermometer cooling chemistry",
    },
    icemelt: {
        on: "science",
        also: [],
        shows: ["science", "time", "temperature"],
        words: "ice melt melting water puddle minutes freezer sun change chemistry",
    },
    magnifier: {
        on: "science",
        also: [],
        shows: ["science", "counting"],
        words: "magnifying glass lens close up salt sugar sand flour rice grains crystals powder chemistry",
    },
    materials: {
        on: "science",
        also: ["home"],
        shows: ["science", "chance"],
        words: "materials made of wood metal plastic glass fabric wool paper cardboard rubber rock brick property waterproof bendy hard see-through chemistry",
    },
    mixture: {
        on: "science",
        also: [],
        shows: ["science"],
        words: "mixture mixed separate dissolve sink float sand salt sugar iron cork water chemistry",
    },
    molecule: {
        on: "science",
        also: [],
        shows: ["science", "counting"],
        words: "molecule atoms ball and stick water oxygen hydrogen carbon dioxide nitrogen methane model chemistry",
    },
    nails: {
        on: "science",
        also: [],
        shows: ["science", "time"],
        words: "rust rusting nails iron jars water air oil salt painted days fair test chemistry",
    },
    particles: {
        on: "science",
        also: [],
        shows: ["science"],
        words: "jar solid liquid gas state particle vibrate move chemistry",
    },
    rocks: {
        on: "science",
        also: ["outdoors"],
        shows: ["science", "chance"],
        words: "rocks granite basalt pumice sandstone chalk limestone marble slate igneous sedimentary metamorphic soak permeable fizz vinegar test chemistry",
    },
    safety: {
        on: "science",
        also: [],
        shows: ["science"],
        words: "safety goggles apron oven glove tray grown-up chemistry",
    },
    sieve: {
        on: "science",
        also: ["food"],
        shows: ["science"],
        words: "sieve separate mixture holes pebbles sand flour rice peas bowl sort size chemistry",
    },
    soiljar: {
        on: "science",
        also: ["outdoors"],
        shows: ["science", "length", "ordering"],
        words: "soil jar layers settle stones sand silt clay humus water rocks chemistry",
    },
    squash: {
        on: "science",
        also: [],
        shows: ["science"],
        words: "squash bend twist stretch shape spring back sponge clay elastic materials chemistry",
    },
    testtubes: {
        on: "science",
        also: [],
        shows: ["science", "capacity", "colour"],
        words: "test tubes rack tube colours fizz bubbles stopper chemistry",
    },
    watercycle: {
        on: "science",
        also: ["outdoors"],
        shows: ["science", "ordering"],
        words: "water cycle evaporation condensation precipitation collection rain cloud sea river sun vapour weather chemistry",
    },
    calendar: { on: "time", also: [], shows: ["calendar"], words: "" },
    clocktower: { on: "places", also: ["time"], shows: ["time"], words: "" },
    coins: { on: "money", also: [], shows: ["money", "counting"], words: "" },
    containers: { on: "measuring", also: ["food"], shows: ["capacity"], words: "" },
    dayloop: {
        on: "page",
        also: ["time"],
        shows: ["calendar"],
        words: "loop ring circled today pencil",
    },
    days: { on: "time", also: [], shows: ["calendar"], words: "week" },
    dialscale: { on: "measuring", also: ["food"], shows: ["weight"], words: "" },
    digital: { on: "time", also: [], shows: ["time"], words: "" },
    elapsed: { on: "time", also: [], shows: ["time"], words: "how long" },
    jug: { on: "measuring", also: ["food"], shows: ["capacity"], words: "" },
    masses: { on: "measuring", also: [], shows: ["weight"], words: "" },
    ruler: { on: "measuring", also: [], shows: ["length"], words: "" },
    schedule: { on: "time", also: [], shows: ["time", "calendar"], words: "timetable" },
    springscale: { on: "measuring", also: ["science"], shows: ["weight"], words: "newton force" },
    stopwatch: { on: "time", also: ["sport"], shows: ["time"], words: "" },
    sundial: {
        on: "time",
        also: ["science"],
        shows: ["time"],
        words: "sundial shadow sun time clock hour",
    },
    tape: { on: "measuring", also: [], shows: ["length"], words: "" },
    thermometer: { on: "measuring", also: ["science"], shows: ["temperature"], words: "" },
    raingauge: {
        on: "measuring",
        also: ["science", "outdoors"],
        shows: ["capacity", "data"],
        words: "rain gauge weather wet millimetres funnel",
    },
    timeline: {
        on: "time",
        also: [],
        shows: ["calendar", "ordering"],
        words: "history years dates",
    },
    yearwheel: { on: "time", also: [], shows: ["calendar"], words: "" },
    angle: { on: "shapes", also: [], shows: ["symmetry"], words: "" },
    areagrid: { on: "sums", also: [], shows: ["times"], words: "grid method long multiplication" },
    bag: { on: "data", also: [], shows: ["chance"], words: "" },
    bargraph: { on: "data", also: [], shows: ["data"], words: "" },
    carroll: { on: "data", also: [], shows: ["chance"], words: "" },
    construction: { on: "shapes", also: [], shows: ["shape"], words: "compass arcs" },
    coords: { on: "shapes", also: [], shows: ["position"], words: "coordinates axes" },
    dotplot: { on: "data", also: [], shows: ["data"], words: "" },
    heads: {
        on: "people",
        also: ["puzzles"],
        shows: ["counting", "ordering"],
        words: "queue position ordinal row",
    },
    linegraph: { on: "data", also: [], shows: ["data"], words: "" },
    logicgrid: {
        on: "data",
        also: ["puzzles"],
        shows: ["puzzles"],
        words: "logic grid deduction clues who owns which tick cross table",
    },
    longdiv: { on: "sums", also: [], shows: ["sharing"], words: "bus stop short division" },
    lshape: {
        on: "shapes",
        also: [],
        shows: ["shape", "length"],
        words: "area perimeter compound",
    },
    mirror: { on: "shapes", also: [], shows: ["symmetry", "halves"], words: "" },
    net: { on: "shapes", also: [], shows: ["shape"], words: "fold cube" },
    picgraph: { on: "data", also: [], shows: ["data"], words: "" },
    plotpoint: { on: "shapes", also: [], shows: ["position"], words: "coordinates point" },
    probscale: { on: "data", also: [], shows: ["chance"], words: "" },
    protractor: { on: "shapes", also: [], shows: ["symmetry"], words: "angle measure" },
    pyramid: { on: "sums", also: ["puzzles"], shows: ["adding", "puzzles"], words: "number wall" },
    reflect: { on: "shapes", also: [], shows: ["symmetry"], words: "" },
    rings: { on: "data", also: [], shows: ["chance"], words: "" },
    setsquare: { on: "shapes", also: [], shows: ["shape", "symmetry"], words: "" },
    shapemarks: { on: "shapes", also: [], shows: ["shape"], words: "equal sides parallel" },
    solid: { on: "shapes", also: [], shows: ["shape"], words: "" },
    spinner: { on: "data", also: ["sport"], shows: ["chance"], words: "" },
    table: { on: "data", also: [], shows: ["data"], words: "" },
    tally: { on: "counting", also: ["data"], shows: ["counting", "data"], words: "" },
    tallytable: { on: "data", also: [], shows: ["data"], words: "" },
    tessellation: { on: "shapes", also: [], shows: ["shape", "patterns"], words: "" },
    venn: { on: "data", also: [], shows: ["chance"], words: "" },
    money: { on: "money", also: [], shows: ["money"], words: "notes" },
    abacus: { on: "place", also: [], shows: ["place", "counting"], words: "" },
    array: { on: "counting", also: [], shows: ["times", "counting"], words: "dots rows" },
    arrowcards: { on: "place", also: [], shows: ["place"], words: "" },
    arrowchain: { on: "sums", also: [], shows: ["adding", "puzzles"], words: "steps chain" },
    balance: { on: "puzzles", also: [], shows: ["puzzles", "weight"], words: "scales equal pans" },
    balanceeq: { on: "sums", also: ["puzzles"], shows: ["puzzles"], words: "equation equals" },
    barmodel: {
        on: "counting",
        also: [],
        shows: ["adding", "bonds", "puzzles"],
        words: "part whole",
    },
    baseten: { on: "place", also: [], shows: ["place"], words: "blocks" },
    beadstring: { on: "counting", also: [], shows: ["counting", "bonds"], words: "beads" },
    cards: { on: "sport", also: [], shows: ["counting", "chance"], words: "playing cards game" },
    change: { on: "money", also: [], shows: ["money", "adding"], words: "" },
    clock: { on: "time", also: [], shows: ["time"], words: "" },
    compare: { on: "counting", also: [], shows: ["ordering"], words: "greater less than signs" },
    comparebars: { on: "counting", also: [], shows: ["ordering", "adding"], words: "difference" },
    decimalsquare: { on: "fractions", also: [], shows: ["decimals"], words: "" },
    digitcards: { on: "place", also: [], shows: ["place", "puzzles"], words: "" },
    dominoes: {
        on: "sport",
        also: ["counting"],
        shows: ["counting", "adding", "patterns"],
        words: "domino dots game",
    },
    doubleline: { on: "fractions", also: [], shows: ["decimals", "times"], words: "ratio scale" },
    equivalent: { on: "fractions", also: [], shows: ["halves"], words: "" },
    fan: { on: "counting", also: ["place"], shows: ["place"], words: "number fan" },
    "fraction.bar": { on: "fractions", also: [], shows: ["halves"], words: "" },
    "fraction.circle": { on: "fractions", also: [], shows: ["halves"], words: "" },
    fractionwall: { on: "fractions", also: [], shows: ["halves"], words: "" },
    gattegno: { on: "place", also: [], shows: ["place"], words: "" },
    geoboard: { on: "shapes", also: [], shows: ["shape"], words: "pegs bands" },
    grid: {
        on: "shapes",
        also: ["fractions"],
        shows: ["shape", "halves", "times"],
        words: "area squares shade",
    },
    hundred: {
        on: "counting",
        also: [],
        shows: ["counting", "adding", "patterns"],
        words: "100 square",
    },
    inequality: { on: "counting", also: [], shows: ["ordering"], words: "" },
    inout: { on: "sums", also: [], shows: ["puzzles", "patterns"], words: "in out table rule" },
    ladder: {
        on: "counting",
        also: [],
        shows: ["counting", "patterns", "ordering"],
        words: "number ladder steps",
    },
    letter: { on: "sums", also: [], shows: ["puzzles"], words: "algebra letter unknown" },
    machine: {
        on: "sums",
        also: [],
        shows: ["puzzles", "times", "adding"],
        words: "function machine rule",
    },
    machinechain: { on: "sums", also: [], shows: ["puzzles"], words: "function machine rule" },
    matchsticks: { on: "puzzles", also: [], shows: ["puzzles", "adding"], words: "sticks" },
    mixed: { on: "fractions", also: [], shows: ["halves"], words: "" },
    nearest: { on: "counting", also: [], shows: ["ordering", "place"], words: "closer nearer" },
    numberball: {
        on: "counting",
        also: ["sport"],
        shows: [],
        words: "game ball number numbered pool lottery bingo",
    },
    numberbond: { on: "counting", also: [], shows: ["bonds", "adding"], words: "" },
    numberline: {
        on: "counting",
        also: [],
        shows: ["counting", "adding", "ordering"],
        words: "jumps",
    },
    ordertrack: { on: "counting", also: [], shows: ["ordering"], words: "" },
    patternblocks: {
        on: "shapes",
        also: ["puzzles"],
        shows: ["shape", "patterns", "halves"],
        words: "",
    },
    percentbar: { on: "fractions", also: [], shows: ["decimals"], words: "" },
    pie: { on: "fractions", also: ["data"], shows: ["halves", "data"], words: "pie chart" },
    placename: { on: "place", also: [], shows: ["place"], words: "" },
    placevalue: { on: "place", also: [], shows: ["place", "counting"], words: "rods cubes" },
    pricetag: { on: "money", also: [], shows: ["money"], words: "" },
    purse: { on: "money", also: [], shows: ["money", "counting"], words: "" },
    pvchart: { on: "place", also: [], shows: ["place"], words: "" },
    ratio: { on: "fractions", also: [], shows: ["decimals", "times"], words: "" },
    receipt: { on: "money", also: [], shows: ["money", "adding"], words: "" },
    rekenrek: { on: "counting", also: [], shows: ["counting", "bonds"], words: "bead frame" },
    rods: { on: "counting", also: [], shows: ["counting", "bonds"], words: "cuisenaire" },
    rounding: { on: "place", also: [], shows: ["place", "ordering"], words: "round nearest" },
    rulemachine: {
        on: "sums",
        also: ["sport"],
        shows: ["patterns", "puzzles"],
        words: "game function machine rule find in out lever cogs gears hopper chute bulb card slot",
    },
    shop: { on: "money", also: ["food"], shows: ["money"], words: "" },
    signchain: { on: "counting", also: [], shows: ["ordering"], words: "greater less than signs" },
    sizeorder: { on: "counting", also: [], shows: ["ordering", "length"], words: "towers tallest" },
    sumtriangle: {
        on: "puzzles",
        also: ["sums"],
        shows: ["adding", "puzzles", "bonds"],
        words: "arithmagon triangle corners sides sums missing",
    },
    tangram: { on: "puzzles", also: ["shapes"], shows: ["shape", "puzzles"], words: "" },
    tenframe: {
        on: "counting",
        also: [],
        shows: ["counting", "bonds", "adding"],
        words: "counters",
    },
    terms: { on: "puzzles", also: [], shows: ["patterns"], words: "growing pattern sequence" },
    till: { on: "money", also: [], shows: ["money"], words: "" },
    towers: {
        on: "counting",
        also: ["puzzles", "shapes"],
        shows: ["counting", "times", "ordering", "puzzles"],
        words: "cubes blocks stack build tower level equal fair share",
    },
    tub: { on: "counting", also: [], shows: ["counting", "bonds"], words: "counters two colours" },
    undercup: {
        on: "counting",
        also: ["sums"],
        shows: ["bonds", "adding", "puzzles"],
        words: "hidden hiding cup counters missing part whole secret",
    },
    unknown: {
        on: "sums",
        also: [],
        shows: ["puzzles", "adding"],
        words: "missing number box equation",
    },
    washingline: {
        on: "counting",
        also: [],
        shows: ["ordering", "counting"],
        words: "washing line pegs",
    },
    balloon: {
        on: "travel",
        also: [],
        shows: ["counting", "weight"],
        words: "hot air balloon sky basket",
    },
    bridge: { on: "places", also: [], shows: ["counting"], words: "arches river" },
    canallock: {
        on: "travel",
        also: ["places"],
        shows: ["capacity", "ordering"],
        words: "canal lock gates water level boat",
    },
    carriage: { on: "travel", also: [], shows: ["counting"], words: "railway" },
    cloud: {
        on: "outdoors",
        also: [],
        shows: ["science", "counting"],
        words: "cloud sky weather rain",
    },
    compass: {
        on: "travel",
        also: ["shapes"],
        shows: ["position", "symmetry"],
        words: "compass rose",
    },
    departureboard: { on: "travel", also: ["time"], shows: ["time"], words: "timetable trains" },
    divingbell: {
        on: "travel",
        also: [],
        shows: ["counting"],
        words: "diving bell underwater sea windows chain reef",
    },
    ferry: { on: "travel", also: [], shows: ["counting"], words: "ferry boat cars crossing bay" },
    fuelgauge: {
        on: "travel",
        also: ["measuring"],
        shows: ["halves"],
        words: "petrol fuel tank full empty",
    },
    jetty: { on: "places", also: ["travel"], shows: ["counting"], words: "posts pier harbour" },
    lighthouse: {
        on: "places",
        also: [],
        shows: ["counting", "patterns"],
        words: "stripes harbour",
    },
    loco: { on: "travel", also: [], shows: [], words: "engine locomotive steam railway" },
    mapkey: {
        on: "travel",
        also: [],
        shows: ["position", "reading"],
        words: "map key legend symbols",
    },
    mapscale: {
        on: "travel",
        also: ["measuring"],
        shows: ["length", "position"],
        words: "map scale km",
    },
    maptitle: {
        on: "travel",
        also: [],
        shows: ["position", "reading"],
        words: "map title name scroll",
    },
    narrowboat: { on: "travel", also: [], shows: ["counting"], words: "canal boat barge windows" },
    paperplane: {
        on: "travel",
        also: [],
        shows: ["symmetry", "shape"],
        words: "paper plane folded flying dart",
    },
    roaddistances: {
        on: "travel",
        also: ["measuring"],
        shows: ["length", "adding"],
        words: "road km",
    },
    ropebridge: {
        on: "travel",
        also: [],
        shows: ["counting", "length"],
        words: "rope bridge planks cross sag",
    },
    ship: { on: "travel", also: [], shows: ["counting"], words: "sailing ship sails portholes" },
    sidings: { on: "travel", also: [], shows: ["puzzles"], words: "railway shunting" },
    signpost: { on: "travel", also: [], shows: ["length", "position"], words: "directions" },
    sledge: {
        on: "travel",
        also: ["outdoors"],
        shows: ["counting"],
        words: "sled sledge snow winter slats",
    },
    station: { on: "places", also: ["time"], shows: ["time"], words: "railway clock" },
    suitcases: { on: "travel", also: ["measuring"], shows: ["weight"], words: "luggage bags" },
    tent: { on: "outdoors", also: ["places"], shows: [], words: "camping" },
    ticket: { on: "travel", also: [], shows: ["money", "time"], words: "train ticket" },
    tractor: {
        on: "travel",
        also: [],
        shows: ["counting"],
        words: "farm tractor bales hay wheels",
    },
    train: { on: "travel", also: [], shows: ["counting", "times"], words: "carriages railway" },
    windsock: {
        on: "travel",
        also: ["outdoors"],
        shows: ["science", "counting"],
        words: "wind sock airfield weather direction",
    },
    ammonite: {
        on: "outdoors",
        also: ["science"],
        shows: ["patterns", "counting"],
        words: "ammonite fossil spiral shell ribs",
    },
    ants: {
        on: "animals",
        also: [],
        shows: ["times", "counting"],
        words: "ants insects six legs line crumbs",
    },
    bats: {
        on: "animals",
        also: [],
        shows: ["counting", "nature"],
        words: "bats cave night echo wings upside down",
    },
    birdhide: {
        on: "places",
        also: ["outdoors"],
        shows: ["nature", "data"],
        words: "hide birdwatching marsh",
    },
    birdrow: { on: "animals", also: [], shows: ["counting", "adding"], words: "birds wire" },
    bumblebee: {
        on: "animals",
        also: [],
        shows: ["counting", "nature"],
        words: "bee bumblebee insect wings pollen flowers",
    },
    camel: { on: "animals", also: [], shows: ["capacity", "counting"], words: "camel hump desert" },
    cobweb: {
        on: "outdoors",
        also: ["animals"],
        shows: ["symmetry", "counting"],
        words: "spider web cobweb dew spokes spiral",
    },
    comet: {
        on: "outdoors",
        also: ["science"],
        shows: ["nature"],
        words: "comet space sky tail stars",
    },
    coral: {
        on: "outdoors",
        also: ["animals"],
        shows: ["nature", "counting"],
        words: "coral reef sea underwater fans spawn ocean",
    },
    crabs: { on: "animals", also: [], shows: ["counting", "times"], words: "legs beach seaside" },
    crops: {
        on: "outdoors",
        also: [],
        shows: ["times", "nature", "calendar"],
        words: "farm field crop wheat seeds grow harvest rows seasons",
    },
    crystals: {
        on: "outdoors",
        also: ["shapes", "science"],
        shows: ["shape", "counting"],
        words: "crystals gems cave prism faces edges corners solid rock",
    },
    dandelion: {
        on: "outdoors",
        also: [],
        shows: ["counting", "adding"],
        words: "dandelion clock seeds flower blow wind",
    },
    daysky: {
        on: "outdoors",
        also: ["science"],
        shows: ["science", "calendar"],
        words: "day night sky moon stars clouds weather",
    },
    dolphins: { on: "animals", also: [], shows: ["counting"], words: "dolphin sea leap pod" },
    dragonfly: {
        on: "animals",
        also: ["outdoors"],
        shows: ["counting", "nature"],
        words: "insect wings marsh pond",
    },
    eagle: { on: "animals", also: [], shows: ["nature"], words: "bird mountains" },
    fennec: { on: "animals", also: [], shows: ["nature"], words: "fennec fox desert ears sand" },
    firs: { on: "outdoors", also: [], shows: ["counting"], words: "trees fir snow woods" },
    fishshoal: {
        on: "animals",
        also: ["counting"],
        shows: ["times", "counting"],
        words: "fish shoal school array rows columns sea reef",
    },
    fossil: {
        on: "outdoors",
        also: ["science"],
        shows: ["halves", "length"],
        words: "fossil skeleton bones skull dinosaur sea reptile cliff history",
    },
    fox: { on: "animals", also: [], shows: ["nature"], words: "woods" },
    frogcycle: {
        on: "outdoors",
        also: ["science", "animals"],
        shows: ["nature", "ordering"],
        words: "frog frogspawn tadpole froglet life cycle pond",
    },
    geese: {
        on: "animals",
        also: [],
        shows: ["counting", "patterns"],
        words: "geese birds flying v formation odd even flock",
    },
    glowworms: {
        on: "animals",
        also: [],
        shows: ["counting", "nature"],
        words: "glow worm cave lights threads silk",
    },
    growstages: {
        on: "outdoors",
        also: ["science"],
        shows: ["science", "nature", "ordering"],
        words: "plant seed grow life cycle",
    },
    gull: { on: "animals", also: [], shows: ["nature"], words: "seagull bird harbour" },
    heron: {
        on: "animals",
        also: ["outdoors"],
        shows: ["nature", "ordering"],
        words: "bird marsh reeds bulrush",
    },
    iceberg: { on: "outdoors", also: ["science"], shows: ["halves", "decimals"], words: "ice sea" },
    kingfisher: { on: "animals", also: [], shows: ["nature"], words: "bird river blue fishing" },
    leafrow: { on: "outdoors", also: [], shows: ["nature", "chance"], words: "leaves" },
    manta: {
        on: "animals",
        also: [],
        shows: ["nature"],
        words: "manta ray sea wings glide ocean reef",
    },
    minibeasts: {
        on: "animals",
        also: ["outdoors"],
        shows: ["counting", "nature"],
        words: "insects bugs ladybird spider beetle spots legs",
    },
    moon: { on: "outdoors", also: [], shows: ["science", "halves"], words: "phase night" },
    oasis: {
        on: "outdoors",
        also: [],
        shows: ["capacity", "nature"],
        words: "oasis desert pool water palms spring rain flowers",
    },
    octopus: {
        on: "animals",
        also: [],
        shows: ["counting", "nature"],
        words: "octopus eight arms tentacles suckers sea reef",
    },
    palms: {
        on: "outdoors",
        also: [],
        shows: ["counting", "times"],
        words: "palm trees coconuts island",
    },
    parrot: { on: "animals", also: [], shows: ["nature"], words: "bird jungle" },
    peaks: { on: "outdoors", also: [], shows: ["ordering"], words: "mountains snow" },
    pond: {
        on: "outdoors",
        also: ["animals"],
        shows: ["counting", "nature"],
        words: "frog fish lily pads",
    },
    rabbits: { on: "animals", also: [], shows: ["counting", "times"], words: "bunny pet ears" },
    rainbow: {
        on: "outdoors",
        also: ["science"],
        shows: ["ordering", "patterns"],
        words: "rainbow colours bands weather light",
    },
    seal: { on: "animals", also: [], shows: ["nature"], words: "seal sea rock whiskers" },
    seasontrees: {
        on: "outdoors",
        also: ["time"],
        shows: ["calendar", "nature"],
        words: "seasons spring summer autumn winter",
    },
    seaturtle: {
        on: "animals",
        also: [],
        shows: ["nature", "counting"],
        words: "turtle sea shell flippers ocean reef life cycle",
    },
    skyisland: {
        on: "outdoors",
        also: ["places"],
        shows: ["counting"],
        words: "floating island sky clouds waterfall layers roots",
    },
    stalactites: {
        on: "outdoors",
        also: ["science"],
        shows: ["length", "ordering"],
        words: "stalactite stalagmite cave column drip grow rock",
    },
    starfish: {
        on: "animals",
        also: ["shapes"],
        shows: ["symmetry", "counting"],
        words: "starfish sea star arms five symmetry beach reef",
    },
    strata: {
        on: "outdoors",
        also: ["science"],
        shows: ["ordering"],
        words: "layers rock cliff strata fossils oldest youngest timeline history",
    },
    toadstools: {
        on: "outdoors",
        also: [],
        shows: ["counting"],
        words: "toadstool mushroom spots red",
    },
    volcano: { on: "outdoors", also: [], shows: [], words: "island mountain" },
    whale: { on: "animals", also: [], shows: ["nature"], words: "sea ocean" },
    face: {
        on: "people",
        also: ["stories"],
        shows: ["reading"],
        words: "feeling emotion mood happy sad cross scared",
    },
    person: {
        on: "people",
        also: ["stories"],
        shows: ["counting", "sharing", "reading"],
        words: "person people child children kid grown-up adult parent grandparent family friend boy girl wheelchair crutches walking stick glasses hearing aid implant headscarf skin hair wave point hold sit",
    },
    umbrellas: {
        on: "people",
        also: ["outdoors"],
        shows: ["counting", "times"],
        words: "umbrella umbrellas rain raindrops puddle wet weather walking town market street panels family",
    },
    "prop.apple": { on: "food", also: ["counting"], shows: ["counting"], words: "fruit" },
    "prop.dice": {
        on: "sport",
        also: ["counting"],
        shows: ["counting", "adding", "chance"],
        words: "dice game",
    },
    "prop.cube": { on: "counting", also: [], shows: ["counting"], words: "cubes blocks" },
    "prop.ball": { on: "counting", also: ["sport"], shows: ["counting"], words: "" },
    "prop.star": { on: "counting", also: ["page"], shows: ["counting"], words: "" },
    "prop.shapes": { on: "shapes", also: [], shows: ["shape"], words: "" },
    "prop.coins": { on: "money", also: [], shows: ["money"], words: "" },
    bubble: { on: "page", also: [], shows: [], words: "speech talk says" },
    note: { on: "page", also: [], shows: [], words: "teacher note tape" },
    icon: {
        on: "apps",
        also: ["page"],
        shows: [],
        words: "icon icons button control home journal map print settings back sign out add help sound",
    },
    newbook: {
        on: "apps",
        also: ["home"],
        shows: ["writing"],
        words: "empty nothing yet first page new exercise book name label pencil welcome start",
    },
    grownup: {
        on: "apps",
        also: ["people"],
        shows: [],
        words: "grown-up parent adult portrait picture avatar face head shoulders stamp hair short long curly bun braids glasses beard headscarf cap grey older",
    },
    "guide.firefly": { on: "page", also: [], shows: [], words: "guide character firefly" },
    "guide.glow": { on: "page", also: [], shows: [], words: "guide character glow light" },
    "guide.hand": { on: "page", also: [], shows: [], words: "guide character hand" },
    "guide.stub": { on: "page", also: [], shows: [], words: "guide character pencil stub" },
    "guide.bird": { on: "page", also: [], shows: [], words: "guide character paper bird" },
    "guide.snail": { on: "page", also: [], shows: [], words: "guide character snail" },
    "guide.dot": { on: "page", also: [], shows: [], words: "guide character dot" },
    albatross: {
        on: "animals",
        also: [],
        shows: ["nature", "length"],
        words: "albatross seabird wings wingspan glide ocean sea waves",
    },
    badger: {
        on: "animals",
        also: ["outdoors"],
        shows: ["nature", "counting"],
        words: "badger stripes striped face black white grey sett woods night dusk nose sniffing legs",
    },
    goat: {
        on: "animals",
        also: ["outdoors"],
        shows: ["nature"],
        words: "goat mountain goat horns beard shaggy white coat rock ledge cliff climbing hooves",
    },
    owlflying: {
        on: "animals",
        also: [],
        shows: ["nature"],
        words: "owl tawny flying night wings moon bird",
    },
    robin: {
        on: "animals",
        also: ["outdoors"],
        shows: ["nature"],
        words: "robin redbreast bird garden fence post window sill winter",
    },
    starlings: {
        on: "animals",
        also: [],
        shows: ["counting", "nature"],
        words: "starlings murmuration flock birds evening dusk sky swirl",
    },
    hedge: {
        on: "outdoors",
        also: [],
        shows: ["counting", "nature"],
        words: "hedge hawthorn hedgerow bush berries haws field edge gate gap meadow",
    },
    log: {
        on: "outdoors",
        also: [],
        shows: ["counting", "nature"],
        words: "log fallen tree trunk rings age years wood moss toadstool toadstools mushroom leaves woods",
    },
    shootingstar: {
        on: "outdoors",
        also: ["science"],
        shows: ["nature"],
        words: "shooting star meteor night sky wish sparkles trail",
    },
    stile: {
        on: "outdoors",
        also: ["places"],
        shows: ["counting"],
        words: "stile fence rails steps field meadow countryside footpath climb over",
    },
    lamppost: {
        on: "places",
        also: ["home"],
        shows: [],
        words: "street lamp lamppost light lantern night pillar box postbox letterbox post letter slot town",
    },
    cablecar: {
        on: "travel",
        also: ["places"],
        shows: ["counting", "times"],
        words: "cable car gondola mountain pylon cabins windows ropeway lift",
    },
    railsignal: {
        on: "travel",
        also: [],
        shows: [],
        words: "railway signal semaphore arm stop go lamp level crossing barrier train track",
    },
    shipwheel: {
        on: "travel",
        also: ["shapes"],
        shows: ["symmetry", "counting"],
        words: "ship's wheel helm steer steering spokes handles angle turn degrees sea sailing",
    },
    runners: {
        on: "sport",
        also: ["people"],
        shows: ["counting", "ordering"],
        words: "runners running race track lane athletics sports day children numbers wheelchair racing",
    },
    airship: {
        on: "travel",
        also: [],
        shows: ["length"],
        words: "airship blimp zeppelin sky fly cabin propeller",
    },
    bookhouse: {
        on: "places",
        also: ["stories"],
        shows: ["reading", "counting"],
        words: "book house library books shelves reading ladder",
    },
    buoy: {
        on: "travel",
        also: ["outdoors"],
        shows: ["counting"],
        words: "buoy bell sea marker bands float boats light",
    },
    flamingos: {
        on: "animals",
        also: [],
        shows: ["nature", "counting"],
        words: "flamingo flamingos pink birds legs water",
    },
    gannet: {
        on: "animals",
        also: [],
        shows: ["nature"],
        words: "gannet seabird dive diving sea fish",
    },
    geyser: {
        on: "outdoors",
        also: ["science"],
        shows: ["science", "temperature"],
        words: "geyser hot spring steam boiling water fountain",
    },
    giantflower: {
        on: "outdoors",
        also: [],
        shows: ["nature"],
        words: "giant flower rainforest bud open petals",
    },
    greatclock: {
        on: "places",
        also: ["time"],
        shows: ["time", "coding"],
        words: "clock tower great clock figures strike hour gears workshop clockwork",
    },
    lampstation: {
        on: "places",
        also: ["coding"],
        shows: ["coding", "counting"],
        words: "lamp lamps lighthouse rock signal code pattern on off binary sea",
    },
    loosepages: {
        on: "writing",
        also: [],
        shows: ["writing", "reading"],
        words: "pages paper sheets wind blowing printed",
    },
    mailboat: {
        on: "travel",
        also: [],
        shows: ["writing", "counting"],
        words: "mail boat post letters sacks harbour quay",
    },
    parakeets: {
        on: "animals",
        also: [],
        shows: ["nature", "counting"],
        words: "parakeets parrots birds green flock forest",
    },
    printingpress: {
        on: "places",
        also: ["writing"],
        shows: ["writing", "letters"],
        words: "printing press print letters type book pages ink",
    },
    puffins: {
        on: "animals",
        also: [],
        shows: ["counting", "nature"],
        words: "puffin puffins seabird rock beak fish sea",
    },
    saltlake: {
        on: "outdoors",
        also: [],
        shows: ["science", "symmetry"],
        words: "salt lake salt flat mirror reflection crust hexagons mountains",
    },
    saltpans: {
        on: "outdoors",
        also: ["science"],
        shows: ["science", "capacity"],
        words: "salt pans evaporate evaporation seawater heaps rake",
    },
    seaplane: {
        on: "travel",
        also: [],
        shows: ["nature"],
        words: "seaplane plane floats water fly propeller",
    },
    seaserpent: {
        on: "stories",
        also: ["travel"],
        shows: ["counting"],
        words: "sea serpent monster doodle old map margin loops",
    },
    swallows: {
        on: "animals",
        also: [],
        shows: ["nature", "counting"],
        words: "swallow swallows birds fork tail summer evening",
    },
    treeplatform: {
        on: "outdoors",
        also: ["places"],
        shows: ["science", "weight"],
        words: "tree platform treehouse rainforest basket pulley rope ladder",
    },
    yachts: {
        on: "travel",
        also: [],
        shows: ["ordering", "counting"],
        words: "yachts sailing boats race regatta sails numbers",
    },
    animals: {
        on: "animals",
        also: [],
        shows: ["counting", "times"],
        words: "farm sheep cow cows duck ducks field legs",
    },
    balloons: {
        on: "home",
        also: [],
        shows: ["counting", "sharing"],
        words: "party balloons string",
    },
    bandstand: {
        on: "places",
        also: ["music"],
        shows: ["counting", "music"],
        words: "park music posts",
    },
    barn: {
        on: "places",
        also: ["animals"],
        shows: ["counting"],
        words: "farm barn hay loft harvest",
    },
    basket: {
        on: "food",
        also: ["counting"],
        shows: ["counting", "adding"],
        words: "apples fruit",
    },
    boxes: {
        on: "counting",
        also: ["home"],
        shows: ["times", "sharing"],
        words: "packs groups left over",
    },
    bubbles: {
        on: "home",
        also: [],
        shows: ["counting", "ordering"],
        words: "soap bubbles float pop play garden",
    },
    bus: { on: "travel", also: [], shows: ["adding", "counting"], words: "passengers" },
    cake: {
        on: "food",
        also: ["fractions"],
        shows: ["halves", "counting"],
        words: "birthday candles slices",
    },
    carousel: {
        on: "places",
        also: ["sport"],
        shows: ["counting"],
        words: "fair fairground merry go round horses lights",
    },
    bottle: {
        on: "home",
        also: ["outdoors", "stories"],
        shows: ["reading", "writing"],
        words: "bottle message letter sea float cork glass washed up",
    },
    chest: { on: "home", also: [], shows: ["counting", "money"], words: "treasure coins" },
    children: {
        on: "people",
        also: [],
        shows: ["sharing", "counting"],
        words: "kids friends people",
    },
    citywalls: {
        on: "places",
        also: [],
        shows: ["counting", "length"],
        words: "city walls castle battlements towers gate history",
    },
    clothesline: {
        on: "home",
        also: ["outdoors"],
        shows: ["patterns", "counting"],
        words: "washing line clothes pegs garden",
    },
    comic: { on: "stories", also: [], shows: ["reading"], words: "strip panels" },
    cottage: { on: "places", also: [], shows: ["counting"], words: "house windows" },
    dog: { on: "animals", also: [], shows: ["reading"], words: "pet puppy ball" },
    "world.door": { on: "places", also: ["home"], shows: [], words: "door way in indoors" },
    easel: {
        on: "home",
        also: [],
        shows: ["patterns"],
        words: "art paint painting palette colours mix picture",
    },
    flowers: { on: "outdoors", also: [], shows: ["counting", "times"], words: "petals garden" },
    gardengate: {
        on: "places",
        also: ["outdoors"],
        shows: ["counting"],
        words: "gate fence garden bars latch open shut field",
    },
    hall: {
        on: "places",
        also: [],
        shows: ["times", "counting"],
        words: "school building windows array bell",
    },
    houses: { on: "places", also: [], shows: ["times", "counting"], words: "street row windows" },
    hut: {
        on: "places",
        also: ["home"],
        shows: ["counting"],
        words: "hut shed art pictures gallery wall",
    },
    lantern: { on: "home", also: [], shows: [], words: "light lamp" },
    library: {
        on: "places",
        also: [],
        shows: ["counting", "reading"],
        words: "library books columns dome steps",
    },
    mice: { on: "animals", also: [], shows: ["counting"], words: "mouse" },
    moorings: {
        on: "places",
        also: ["stories"],
        shows: ["reading"],
        words: "quay boats harbour clues",
    },
    observatory: {
        on: "places",
        also: ["science"],
        shows: [],
        words: "observatory dome telescope stars space",
    },
    picturecards: { on: "stories", also: [], shows: ["reading"], words: "pick pictures" },
    plate: { on: "food", also: [], shows: ["sharing", "counting"], words: "biscuits cakes" },
    skater: {
        on: "people",
        also: ["sport"],
        shows: ["nature"],
        words: "ice skating skate winter child",
    },
    snowman: {
        on: "outdoors",
        also: ["home"],
        shows: ["counting", "ordering"],
        words: "snow winter buttons carrot hat",
    },
    starrow: { on: "page", also: [], shows: ["rewards", "counting"], words: "sticker chart" },
    storymap: { on: "stories", also: [], shows: ["reading", "ordering"], words: "story path plot" },
    street: {
        on: "places",
        also: ["stories"],
        shows: ["reading", "position"],
        words: "clues houses",
    },
    sweetjar: { on: "food", also: [], shows: ["counting"], words: "sweets candy jar" },
    pizza: { on: "food", also: ["fractions"], shows: ["halves"], words: "slices toppings" },
    chocolate: {
        on: "food",
        also: ["fractions"],
        shows: ["halves", "times"],
        words: "bar squares",
    },
    eggbox: {
        on: "food",
        also: ["counting"],
        shows: ["times", "counting", "bonds"],
        words: "eggs dozen six",
    },
    bakingtray: { on: "food", also: [], shows: ["times", "counting"], words: "buns cakes tray" },
    spoons: { on: "food", also: ["measuring"], shows: ["capacity"], words: "teaspoon tablespoon" },
    recipe: { on: "food", also: [], shows: ["capacity", "reading", "times"], words: "ingredients" },
    mixingbowl: { on: "food", also: [], shows: ["capacity"], words: "bowl mix baking" },
    pile: {
        on: "food",
        also: ["measuring"],
        shows: ["weight"],
        words: "flour sugar ingredient scoop",
    },
    worktop: {
        on: "food",
        also: ["home"],
        shows: [],
        words: "game kitchen worktop counter cupboards units doors sink tiles",
    },
    oven: {
        on: "food",
        also: ["home"],
        shows: ["time", "counting"],
        words: "oven cooker stove hob rings timer dial minutes buns tray baking bake kitchen hot lit",
    },
    stickers: { on: "page", also: [], shows: ["rewards"], words: "" },
    callout: { on: "page", also: [], shows: [], words: "tip" },
    divider: { on: "page", also: [], shows: [], words: "" },
    pinned: { on: "page", also: [], shows: [], words: "card pin" },
    steps: { on: "page", also: [], shows: ["rewards"], words: "progress dots" },
    choice: { on: "page", also: [], shows: [], words: "options pick multiple choice answer" },
    pattern: { on: "puzzles", also: [], shows: ["patterns"], words: "" },
    swing: {
        on: "home",
        also: ["outdoors"],
        shows: ["counting", "time"],
        words: "garden play swing pendulum",
    },
    temple: {
        on: "places",
        also: ["puzzles"],
        shows: ["adding", "puzzles"],
        words: "steps number wall",
    },
    tower: {
        on: "places",
        also: [],
        shows: ["counting", "ordering"],
        words: "castle tower old history stone courses flag",
    },
    tree: {
        on: "outdoors",
        also: [],
        shows: ["counting", "adding"],
        words: "apples fruit orchard",
    },
    well: {
        on: "places",
        also: ["measuring"],
        shows: ["capacity", "counting"],
        words: "well bucket water rope stones litres",
    },
    windmill: { on: "places", also: [], shows: ["counting", "symmetry"], words: "sails turn" },
    "world.window": {
        on: "places",
        also: ["home"],
        shows: [],
        words: "window weather rain snow indoors",
    },
    envelope: {
        on: "home",
        also: ["stories"],
        shows: ["reading", "counting"],
        words: "letter post mail stamp code email",
    },
    exercisebook: {
        on: "home",
        also: ["writing"],
        shows: ["counting", "writing"],
        words: "book notebook journal exercise cover label name school",
    },
    tablet: {
        on: "home",
        also: [],
        shows: ["counting"],
        words: "screen ipad device children turns",
    },
    poststamp: {
        on: "home",
        also: ["stories"],
        shows: ["money", "adding"],
        words: "stamp post letter envelope postage perforated value quiet square grown-up",
    },
    postmark: {
        on: "stories",
        also: ["home"],
        shows: ["reading", "calendar"],
        words: "post letter stamp date town cancel",
    },
    weave: {
        on: "art",
        also: [],
        shows: ["patterns", "colour"],
        words: "weave weaving over under strips warp weft paper pattern",
    },
    paintbox: {
        on: "art",
        also: [],
        shows: ["colour"],
        words: "paints tin pans watercolour",
    },
    mixingtray: {
        on: "art",
        also: [],
        shows: ["colour"],
        words: "tray wells mix palette",
    },
    palette: {
        on: "art",
        also: [],
        shows: ["colour"],
        words: "palette blobs brush",
    },
    paintpots: {
        on: "art",
        also: [],
        shows: ["colour", "adding"],
        words: "pots jars mix makes",
    },
    arttools: {
        on: "art",
        also: ["home"],
        shows: ["colour"],
        words: "pencil crayon felt pen marker brush tools stamp eraser",
    },
    colourwheel: {
        on: "art",
        also: [],
        shows: ["colour"],
        words: "wheel primary secondary opposite complementary warm cool",
    },
    tintladder: {
        on: "art",
        also: [],
        shows: ["colour", "ordering"],
        words: "tint shade lighter darker white black",
    },
    paintsheet: {
        on: "art",
        also: ["page"],
        shows: ["colour", "symmetry"],
        words: "sheet paper paint answer mirror layers",
    },
    stamps: {
        on: "art",
        also: [],
        shows: ["colour", "patterns", "symmetry"],
        words: "print printing block stamp repeat",
    },
    printrow: {
        on: "art",
        also: ["puzzles"],
        shows: ["patterns", "colour"],
        words: "repeat pattern border print next",
    },
    mirrorpick: {
        on: "art",
        also: ["puzzles"],
        shows: ["symmetry", "patterns"],
        words: "mirror symmetry butterfly wings print",
    },
    dots: {
        on: "art",
        also: [],
        shows: ["colour"],
        words: "dots pointillism seurat artist",
    },
    layers: {
        on: "art",
        also: ["outdoors"],
        shows: ["colour"],
        words: "landscape hills far near distance layers",
    },
    rubbing: {
        on: "art",
        also: ["outdoors"],
        shows: ["colour", "counting"],
        words: "rubbing leaf veins texture crayon",
    },
    stencil: {
        on: "art",
        also: [],
        shows: ["colour", "shape"],
        words: "stencil hole shape cut out collage geometric organic",
    },
    sunprint: {
        on: "art",
        also: ["outdoors"],
        shows: ["colour", "counting"],
        words: "sun print cyanotype blue fern anna atkins",
    },
    lines: {
        on: "art",
        also: [],
        shows: ["patterns"],
        words: "line lines zigzag wavy dotted spiral straight kinds",
    },
    linewalk: {
        on: "art",
        also: [],
        shows: ["counting", "patterns"],
        words: "line walk loops klee drawing",
    },
    oneline: {
        on: "art",
        also: ["puzzles"],
        shows: ["shape", "puzzles"],
        words: "one line pencil euler house envelope",
    },
    collage: {
        on: "art",
        also: [],
        shows: ["shape", "counting"],
        words: "collage cut paper shapes geometric organic boat fish house",
    },
    radial: {
        on: "art",
        also: [],
        shows: ["symmetry", "patterns"],
        words: "radial turn round rotate kaleidoscope pattern",
    },
    tilerepeat: {
        on: "art",
        also: [],
        shows: ["patterns"],
        words: "tile repeat wallpaper half-drop morris pattern",
    },
    stilllife: {
        on: "art",
        also: ["food"],
        shows: ["colour"],
        words: "still life light shadow shading apple cup drawing",
    },
    tonescale: {
        on: "art",
        also: [],
        shows: ["ordering"],
        words: "tone shading light dark pencil value scale",
    },
    "svg.cat": { on: "animals", also: [], shows: ["counting", "reading"], words: "pet kitten" },
    "svg.duck": {
        on: "animals",
        also: [],
        shows: ["counting", "reading"],
        words: "bird pond farm",
    },
    "svg.hen": { on: "animals", also: [], shows: ["counting"], words: "chicken farm egg bird" },
    "excalidraw.owl": { on: "animals", also: [], shows: ["reading"], words: "bird night branch" },
    "strokes.hedgehog": { on: "animals", also: [], shows: ["nature"], words: "garden spines" },
    "svg.bicycle": { on: "travel", also: [], shows: ["counting"], words: "bike cycle wheels" },
    "svg.kite": { on: "home", also: [], shows: ["halves"], words: "toy wind" },
    "svg.rocket": { on: "travel", also: [], shows: ["counting"], words: "space countdown" },
    "svg.fish-tank": {
        on: "animals",
        also: ["home"],
        shows: ["counting", "ordering"],
        words: "pet fish aquarium",
    },
    "svg.sandcastle": {
        on: "outdoors",
        also: [],
        shows: ["ordering", "counting"],
        words: "beach seaside",
    },
    "excalidraw.wheelbarrow": { on: "outdoors", also: [], shows: [], words: "garden load" },
    "strokes.bunting": { on: "home", also: [], shows: ["patterns"], words: "flags party" },
    "svg.boat": { on: "travel", also: [], shows: [], words: "sea sail" },
    "svg.cup": { on: "food", also: ["home"], shows: ["capacity"], words: "mug drink tea" },
    "svg.pencil": { on: "home", also: [], shows: ["length"], words: "school measure" },
    "strokes.sun": { on: "outdoors", also: [], shows: ["science"], words: "sky weather" },
    "svg.kitchen-counter": {
        on: "food",
        also: ["home"],
        shows: [],
        words: "kitchen worktop kettle setting",
    },
    "svg.shop-front": { on: "places", also: ["money"], shows: ["money"], words: "shop setting" },
    "svg.market-stall": {
        on: "money",
        also: ["places", "food"],
        shows: ["money"],
        words: "market stall fruit setting",
    },
    "svg.bedroom-shelf": { on: "home", also: [], shows: [], words: "bedroom books plant setting" },
    "svg.birthday-table": {
        on: "food",
        also: ["home"],
        shows: ["counting", "sharing"],
        words: "party birthday cake candles setting",
    },
    "svg.treehouse": { on: "outdoors", also: ["places"], shows: [], words: "tree ladder setting" },
    "excalidraw.garden": {
        on: "outdoors",
        also: [],
        shows: ["nature"],
        words: "garden flowers fence setting",
    },
    "strokes.hills": {
        on: "outdoors",
        also: [],
        shows: ["length"],
        words: "landscape path setting",
    },
    "arcade.sling": { on: "sport", also: [], shows: [], words: "game sling catapult launch" },
    hoop: { on: "sport", also: [], shows: [], words: "game hoop ring fly through" },
    tackle: {
        on: "sport",
        also: [],
        shows: ["nature"],
        words: "game fishing hook float bait line",
    },
    die: {
        on: "sport",
        also: ["counting"],
        shows: ["counting", "adding", "chance"],
        words: "dice die roll throw tumble game",
    },
    shutbox: {
        on: "sport",
        also: ["puzzles"],
        shows: ["adding", "counting", "chance"],
        words: "shut the box dice game numbers board",
    },
    shuttile: {
        on: "sport",
        also: [],
        shows: ["counting"],
        words: "shut the box number tile hinge game",
    },
    goalposts: { on: "sport", also: [], shows: [], words: "football goal net" },
    grandstand: {
        on: "sport",
        also: ["places"],
        shows: ["times", "counting"],
        words: "seats stadium rows",
    },
    longjump: { on: "sport", also: ["measuring"], shows: ["length"], words: "" },
    medalrow: { on: "sport", also: [], shows: ["ordering"], words: "gold silver bronze medals" },
    podium: { on: "sport", also: [], shows: ["ordering"], words: "first second third winners" },
    racecar: { on: "sport", also: ["travel"], shows: [], words: "car speed" },
    racecircuit: { on: "sport", also: [], shows: ["position"], words: "track" },
    racetrack: { on: "sport", also: [], shows: ["length"], words: "running race lanes metres" },
    scoreboard: { on: "sport", also: [], shows: ["adding", "data"], words: "score goals" },
    target: { on: "sport", also: [], shows: ["adding"], words: "darts archery points" },
    teamgrid: {
        on: "sport",
        also: ["people"],
        shows: ["times", "counting"],
        words: "shirts numbers team",
    },
    rocket: {
        on: "travel",
        also: ["sport"],
        shows: ["science"],
        words: "game cover rocket space moon mars engine flame land",
    },
    "arcade.road": {
        on: "travel",
        also: ["sport"],
        shows: ["length", "ordering"],
        words: "game race road lanes number line",
    },
    raft: {
        on: "travel",
        also: ["sport"],
        shows: ["counting", "sharing"],
        words: "game raft logs river float flag post sheep boat",
    },
    railway: {
        on: "travel",
        also: ["sport"],
        shows: ["ordering"],
        words: "game railway rails sleepers track line ballast yard train",
    },
    liftpit: {
        on: "travel",
        also: ["sport", "science"],
        shows: ["ordering"],
        words: "game lift pit platform cable wheel gantry yard siding stack",
    },
    yardlever: {
        on: "travel",
        also: ["sport", "science"],
        shows: ["ordering"],
        words: "game lever points handle yard switch",
    },
    coupling: {
        on: "travel",
        also: ["sport"],
        shows: ["ordering"],
        words: "game coupling hook eye chain carriage train link",
    },
    bufferstop: {
        on: "travel",
        also: ["sport"],
        shows: ["ordering"],
        words: "game buffer stop railway end line",
    },
    orderboard: {
        on: "travel",
        also: ["sport"],
        shows: ["ordering"],
        words: "game board sign order train carriages numbers make up",
    },
    rowboat: {
        on: "travel",
        also: ["sport"],
        shows: ["length"],
        words: "game rowing boat oar rower river row jetty",
    },
    mooringbuoy: {
        on: "travel",
        also: ["sport", "outdoors"],
        shows: ["length"],
        words: "game buoy mooring float ring river metres tie up",
    },
    "arcade.ground": { on: "outdoors", also: [], shows: [], words: "game ground grass" },
    meadow: {
        on: "outdoors",
        also: [],
        shows: ["nature"],
        words: "game meadow field grass daisies clover ground from above",
    },
    sea: {
        on: "outdoors",
        also: ["travel"],
        shows: ["nature"],
        words: "game sea water waves sand seabed weed underwater",
    },
    dig: {
        on: "outdoors",
        also: ["travel"],
        shows: ["position"],
        words: "dig hole spade shovel treasure x marks the spot hunt map square",
    },
    current: {
        on: "outdoors",
        also: ["science", "sport"],
        shows: ["length"],
        words: "game current river water flow streaks stream",
    },
    reeds: {
        on: "outdoors",
        also: ["sport"],
        shows: ["counting"],
        words: "reeds rushes stream bank pond water plants",
    },
    steppingstone: {
        on: "outdoors",
        also: ["sport"],
        shows: ["counting", "adding", "ordering"],
        words: "game stepping stone stream number line hop rabbit sink",
    },
    crane: {
        on: "science",
        also: ["places"],
        shows: ["weight"],
        words: "game cover crane jib tower lift",
    },
    fulcrum: {
        on: "science",
        also: [],
        shows: ["weight"],
        words: "game pivot fulcrum stand see-saw lever",
    },
    seesawplank: {
        on: "science",
        also: ["sport"],
        shows: ["weight", "times"],
        words: "game see-saw seesaw plank steps pivot balance level turning lever",
    },
    seesawprops: {
        on: "science",
        also: ["puzzles"],
        shows: ["weight"],
        words: "see-saw seesaw props prop held level plank balance support",
    },
    tap: {
        on: "measuring",
        also: ["food"],
        shows: ["capacity"],
        words: "water fill jug sink kitchen",
    },
    catchscale: {
        on: "measuring",
        also: ["sport"],
        shows: ["weight", "adding"],
        words: "game scale scales weigh catch fish dial needle kilogram gram",
    },
    scalepole: {
        on: "measuring",
        also: ["counting"],
        shows: ["length", "halves", "decimals"],
        words: "game pole scale number line height flag fraction",
    },
    riverpost: {
        on: "measuring",
        also: ["travel", "sport"],
        shows: ["length"],
        words: "game post metres river marker distance plate",
    },
    "arcade.puff": { on: "page", also: [], shows: [], words: "game dust cloud landing" },
    "fx.sparkle": {
        on: "page",
        also: [],
        shows: ["rewards"],
        words: "game sparkle twinkle star burst",
    },
    "fx.drop": { on: "page", also: [], shows: [], words: "game drop water splash" },
    fish: {
        on: "animals",
        also: ["outdoors"],
        shows: ["weight", "ordering"],
        words: "game fish tag weigh heavy catch sea",
    },
    sheep: {
        on: "animals",
        also: ["outdoors"],
        shows: ["counting", "sharing"],
        words: "game sheep lamb farm flock wool graze",
    },
    swimmingrabbit: {
        on: "animals",
        also: ["sport"],
        shows: ["counting"],
        words: "game rabbit swimming water stream splash",
    },
    cakeknife: {
        on: "food",
        also: ["sport"],
        shows: ["halves", "sharing"],
        words: "game knife cut slice",
    },
    longcake: {
        on: "food",
        also: ["fractions", "sport"],
        shows: ["halves", "sharing"],
        words: "game cake sponge icing candles cut slice piece share equal birthday third quarter",
    },
    carrot: {
        on: "food",
        also: ["outdoors", "sport"],
        shows: ["counting"],
        words: "carrot vegetable rabbit orange leaves",
    },
    pegboard: {
        on: "data",
        also: ["sport"],
        shows: ["chance", "data", "counting"],
        words: "game cover peg board galton chance tubes bar chart tally",
    },
    sheeppen: {
        on: "places",
        also: ["outdoors"],
        shows: ["sharing", "times"],
        words: "game pen fold hurdles fence gate farm sheep groups",
    },
    shoveboard: {
        on: "money",
        also: ["sport"],
        shows: ["money", "adding"],
        words: "game shove penny coins counter felt rim board shuffleboard price",
    },
    joindots: {
        on: "puzzles",
        also: ["counting"],
        shows: ["counting", "patterns", "times"],
        words: "dot to dot join the dots connect the dots count on skip counting count in twos fives tens back negative tenths picture",
    },
};
