// The book island: a round island in the southern sea off the home isle, where a tall book house
// stands in a garden of clipped hedges and its shelves fill as stories are read. The place the
// reading lessons bring a child to, in any year.
import type { World } from "./types";

export const bookIsland: World = {
    id: "book-island",
    name: "The book island",
    about: "A round island on a golden afternoon, with clipped hedges, a path of lettered stepping stones, an owl in the garden and a tall book house whose shelves fill as the stories are read. A place for the reading lessons, in any year.",
    mood: "a golden reading afternoon",
    arrive: "This is the book island. Find a story.",
    light: { ground: "mint", sky: "glow", low: "tang", accent: "berry", wash: 0.7 },
    ground: "hedges",
    path: "letters",
    horizon: {
        far: [
            { art: "tree", at: 0.1, k: 0.8, params: { fruit: 3, fallen: 1 } },
            { art: "book-house", at: 0.44, k: 0.6, params: { floors: 3, full: 1 } },
            { art: "hedge", at: 0.8, k: 0.7, params: { clumps: 3, berries: 0, gap: 0 } },
        ],
        gate: "book-house",
    },
    landmarks: ["book-house", "story-sign", "lantern", "shelf"],
    creatures: ["owl", "cat", "rabbit"],
    weather: "clear",
    seasons: ["autumn"],
    guide: "dot",
    reaches: [
        { art: "owl", when: ["skill:logic"], says: "All, some or none? Think it through." },
        {
            art: "lantern",
            when: ["skill:reading.phonics", "skill:reading.blending"],
            says: "Say each sound, then blend them.",
        },
        {
            art: "rabbit",
            when: ["skill:reading.rhyme", "skill:reading.poetry"],
            says: "Read it aloud. Hear the rhyme.",
        },
        {
            art: "book-house",
            when: ["skill:reading.story-structure", "art:storymap"],
            says: "Every story has a start, middle, end.",
        },
        { art: "cat", when: ["skill:reading.characters"], says: "Who is in this story?" },
        {
            art: "story-sign",
            when: ["skill:reading.text-features", "skill:reading.instructions"],
            says: "Read the sign before you go in.",
        },
        {
            art: "shelf",
            when: ["skill:reading.vocabulary", "skill:reading.morphology"],
            says: "Every book here holds new words.",
        },
        {
            art: "owl",
            when: ["skill:reading.inference"],
            says: "Look closely. What does it not say?",
        },
        { art: "book-house", when: ["subject:reading"], says: "Find a book. Read it aloud." },
    ],
    offers: {
        landmarks: ["book-house", "story-sign", "lantern", "shelf", "tree"],
        creatures: ["owl", "cat", "rabbit", "mouse"],
        grounds: ["mint", "glow"],
        guides: ["dot", "firefly", "snail"],
        weather: ["clear", "breezy"],
    },
    wants: [
        {
            what: "A reading tree with a swing seat",
            why: "Somewhere outdoors to sit with a book, and a picture for the poems about places that the reading lessons bring.",
        },
        {
            what: "A little box of books on a post",
            why: "Books left for anyone to borrow, with a sign on its door to read, and a start for a lesson about looking after shared things.",
        },
    ],
    chapter: {
        story: "Not a term's world but the place the reading lessons bring a child to, in any year. Stepping stones lettered from A to Z lead through clipped hedges to a book house whose shelves wait to be filled.",
        moment: {
            art: "book-house",
            says: "Every shelf in the book house is full.",
            params: { floors: 3, full: 1 },
            before: { floors: 3, full: 0 },
        },
        secret: { art: "cat", says: "A cat asleep on a pile of books." },
        by: "sea",
        rare: { art: "swallows", way: "sky", from: "left" },
    },
    site: {
        kind: "track",
        hosts: {
            subjects: [],
            lessons: [
                "reading-letter-sounds",
                "reading-blending-sounds",
                "reading-word-ladders",
                "reading-words-we-know",
                "reading-rhymes",
                "reading-a-sentence-and-a-full-stop",
                "reading-which-picture",
                "reading-read-the-clues",
                "reading-two-letters-one-sound",
                "reading-contractions-and-endings",
                "reading-clapping-the-beats",
                "reading-two-words-make-one",
                "reading-what-the-page-says",
                "reading-who-is-in-the-story",
                "reading-comic-strips",
                "reading-following-a-recipe",
                "reading-how-do-they-feel",
                "reading-what-the-word-means",
                "reading-prefix-bricks",
                "reading-finding-the-answer",
                "reading-putting-the-story-in-order",
                "reading-story-maps",
                "reading-labelled-diagrams",
                "reading-timetables",
                "reading-a-map-with-a-key",
                "reading-the-title",
                "thinking-in-words",
                "reading-suffixes",
                "reading-shades-of-meaning",
                "reading-puzzles",
                "reading-a-poem-to-read-aloud",
                "reading-contents-pages",
                "reading-an-index-and-a-glossary",
                "reading-what-it-does-not-say",
                "reading-fact-and-opinion",
                "reading-a-postcard-from-the-sea",
            ],
            label: "reading and stories",
            needs: "Longer stories read over several days, which the reading track would bring.",
        },
        land: { terrain: "book-island", near: ["meadow"] },
    },
    map: {
        spots: [
            { art: "owl", x: 440, y: 60, k: 0.65, is: "life" },
            { art: "tree", x: -520, y: 180, k: 0.6, params: { fruit: 0, fallen: 0 } },
            {
                art: "book-house",
                x: 40,
                y: 330,
                k: 1.05,
                is: "gate",
                params: { floors: 3, full: 0 },
            },
            { art: "story-sign", x: -430, y: 420, k: 0.6 },
            { art: "cat", x: 660, y: 440, k: 0.5, is: "secret" },
        ],
        stamp: { x: -640, y: -420 },
        isle: true,
    },
};
